import { sourceSnippetByKey, type SourceSnippet } from "./source-snippets.generated";

export type Concept = {
  code: string;
  title: string;
  subtitle: string;
  body: string;
  boundary: string;
};

export type FlowStep = {
  label: string;
  actor: string;
  action: string;
  before: string;
  after: string;
  detail: string;
  signal: string;
};

export type DataZone = {
  code: string;
  name: string;
  kind: string;
  owner: string;
  value: string;
  mutation: string;
  rule: string;
};

export type DataRoute = {
  data: string;
  from: string;
  via: string;
  to: string;
  guarantee: string;
};

export type InterviewQuestion = {
  tag: string;
  question: string;
  answer: string;
};

export type LessonDetail = {
  number: string;
  stage: number;
  title: string;
  shortTitle: string;
  english: string;
  hook: string;
  lead: string;
  outcome: string;
  accent: "cyan" | "amber" | "green" | "red";
  concepts: Concept[];
  flowTitle: string;
  flowLead: string;
  flow: FlowStep[];
  zones: DataZone[];
  routes: DataRoute[];
  sourceKeys: string[];
  exercise: {
    title: string;
    summary: string;
    requirements: string[];
    testCommand: string;
    expected: string;
  };
  runClass: string;
  interview: InterviewQuestion[];
  finish: string;
};

export type CourseTab = {
  number: string;
  stage: number;
  shortTitle: string;
  title: string;
};

export const stageLabels = [
  "并发语义与线程协作",
  "锁、同步器与并发结构",
  "任务执行与现代并发",
  "生产能力与综合实战",
] as const;

export const courseTabs: CourseTab[] = [
  { number: "01", stage: 1, shortTitle: "JMM", title: "并发问题与 Java 内存模型" },
  { number: "02", stage: 1, shortTitle: "volatile", title: "volatile、synchronized 与安全发布" },
  { number: "03", stage: 1, shortTitle: "中断", title: "线程生命周期、中断与取消" },
  { number: "04", stage: 1, shortTitle: "CAS", title: "CAS、原子类与高竞争计数" },
  { number: "05", stage: 2, shortTitle: "AQS", title: "AQS、ReentrantLock 与 Condition" },
  { number: "06", stage: 2, shortTitle: "同步器", title: "同步工具与并发故障" },
  { number: "07", stage: 2, shortTitle: "CHM", title: "ConcurrentHashMap 与并发集合" },
  { number: "08", stage: 2, shortTitle: "队列", title: "并发队列与生产消费" },
  { number: "09", stage: 3, shortTitle: "线程池", title: "ThreadPoolExecutor 原理" },
  { number: "10", stage: 3, shortTitle: "Future", title: "线程池工程实践、Future 与调度" },
  { number: "11", stage: 3, shortTitle: "CF", title: "CompletableFuture 异步编排" },
  { number: "12", stage: 3, shortTitle: "ForkJoin", title: "ForkJoinPool 与任务模型选型" },
  { number: "13", stage: 3, shortTitle: "虚拟线程", title: "虚拟线程与结构化并发" },
  { number: "14", stage: 4, shortTitle: "可靠性", title: "并发设计模式与可靠性" },
  { number: "15", stage: 4, shortTitle: "诊断", title: "并发测试、诊断与性能" },
  { number: "16", stage: 4, shortTitle: "综合项目", title: "高并发多下游聚合服务" },
];

export const lessonDetails: LessonDetail[] = [
  {
    number: "02",
    stage: 1,
    title: "volatile、synchronized 与安全发布",
    shortTitle: "可见性不等于原子性",
    english: "PUBLICATION & MUTUAL EXCLUSION",
    hook: "让另一个线程看到一个引用，还不够。",
    lead:
      "这一课把“看见新值”“独占修改状态”“看见完整对象”拆成三份不同契约，再用 volatile、监视器和不可变快照逐一建立保证。",
    outcome: "能为共享状态选择正确的可见性、互斥与发布方案。",
    accent: "cyan",
    concepts: [
      {
        code: "V",
        title: "volatile 发布边",
        subtitle: "visibility + ordering",
        body: "对同一个 volatile 字段的写 happens-before 后续读；写前普通写随引用一起对读取者可见。",
        boundary: "不提供 ++、check-then-act 或多字段不变量的互斥。",
      },
      {
        code: "M",
        title: "监视器临界区",
        subtitle: "mutual exclusion",
        body: "同一监视器同时提供互斥和 unlock→lock 的内存语义，复合状态转换在临界区内完成。",
        boundary: "读写锁住不同对象，就既没有互斥，也没有需要的同步边。",
      },
      {
        code: "P",
        title: "不可变快照",
        subtitle: "safe publication",
        body: "更新线程先在局部构造完整对象，再用一次 volatile 写替换引用；读取者在单一版本上完成全部操作。",
        boundary: "final 的初始化安全性要求构造期间没有 this 逸出。",
      },
    ],
    flowTitle: "不可变配置如何安全流向读取线程",
    flowLead:
      "逐步观察数据先在线程本地完成，再通过一条 volatile 引用发布。读取者不会拼出半新半旧的配置。",
    flow: [
      {
        label: "准备旧版本",
        actor: "共享堆",
        action: "current → Settings v0",
        before: "version=0 / timeout=100",
        after: "读取者可继续使用 v0",
        detail: "旧快照保持不可变，更新开始时不会被原地修改。",
        signal: "STABLE SNAPSHOT",
      },
      {
        label: "局部构造",
        actor: "writer stack",
        action: "new Settings(v1)",
        before: "共享 current 仍指向 v0",
        after: "candidate=v1 完整构造",
        detail: "version、timeout、retries 和 checksum 都先在线程本地形成一致对象。",
        signal: "NO SHARED MUTATION",
      },
      {
        label: "发布引用",
        actor: "writer",
        action: "volatile current = v1",
        before: "current → v0",
        after: "current → v1",
        detail: "一次 volatile 写发布整个已构造快照，并建立写前动作的可见性。",
        signal: "RELEASE EDGE",
      },
      {
        label: "读取引用",
        actor: "reader",
        action: "snapshot = current",
        before: "可能最后一次读到 v0",
        after: "volatile 读取得 v1",
        detail: "读取者只取一次引用，随后在同一个对象版本上读取所有相关字段。",
        signal: "ACQUIRE EDGE",
      },
      {
        label: "校验一致",
        actor: "reader stack",
        action: "checksum(fields)",
        before: "snapshot=v1",
        after: "consistent=true",
        detail: "快照内部不再变化，校验不会跨版本混合。",
        signal: "INVARIANT HOLDS",
      },
      {
        label: "应用到 DCL",
        actor: "singleton",
        action: "volatile + second check",
        before: "instance=null",
        after: "所有线程共享完整实例",
        detail: "锁内第二次检查防重复创建，volatile 防止观察到未完成构造效果。",
        signal: "SAFE PUBLICATION",
      },
    ],
    zones: [
      {
        code: "W",
        name: "candidate",
        kind: "线程本地",
        owner: "config-writer",
        value: "Settings v1",
        mutation: "构造期间一次写完",
        rule: "未发布前不与其他线程共享。",
      },
      {
        code: "H",
        name: "current",
        kind: "共享 volatile 引用",
        owner: "ConfigRepository",
        value: "v0 → v1",
        mutation: "整引用替换",
        rule: "写读之间建立 happens-before。",
      },
      {
        code: "I",
        name: "Settings",
        kind: "不可变堆对象",
        owner: "所有读取者共享",
        value: "4 个一致字段",
        mutation: "构造后不修改",
        rule: "读取过程无需逐字段加锁。",
      },
      {
        code: "L",
        name: "sequence",
        kind: "共享可变整数",
        owner: "SequenceExercise",
        value: "n → n+1",
        mutation: "read-modify-write",
        rule: "volatile 不够，必须用同一监视器保护复合操作。",
      },
    ],
    routes: [
      {
        data: "配置字段",
        from: "writer 局部变量",
        via: "Settings 构造器",
        to: "不可变对象",
        guarantee: "对象先完整构造",
      },
      {
        data: "Settings 引用",
        from: "writer",
        via: "volatile write/read",
        to: "reader snapshot",
        guarantee: "发布前写对读取者可见",
      },
      {
        data: "DCL instance",
        from: "锁内构造",
        via: "volatile 引用",
        to: "无锁快速路径",
        guarantee: "禁止半初始化观察",
      },
      {
        data: "sequence",
        from: "旧值 n",
        via: "同一 monitor 临界区",
        to: "唯一新值 n+1",
        guarantee: "互斥 + unlock→lock",
      },
    ],
    sourceKeys: ["02-publication", "02-dcl", "02-exercise"],
    exercise: {
      title: "修复线程安全序号生成器",
      summary:
        "不使用原子类，让多个线程得到不重复的连续序号，并让 current() 看见已完成更新。",
      requirements: [
        "next() 的读取、加一、写回必须不可分割",
        "next() 与 current() 使用同一个监视器",
        "说明该监视器建立的 happens-before",
        "比较“只加 volatile”和“只同步 next()”为什么不完整",
      ],
      testCommand: "mvn -Dtest=SequenceExerciseTest test",
      expected: "并发生成的序号无重复、无缺口，current 等于最终序号。",
    },
    runClass: "com.caesaemc.juc.lesson02.Lesson02Application",
    interview: [
      {
        tag: "语义",
        question: "volatile 能保证原子性吗？",
        answer: "不能。它提供可见性与特定有序性，value++ 仍是读取、计算、写回三个动作。",
      },
      {
        tag: "选型",
        question: "volatile 与 synchronized 怎么选？",
        answer: "独立状态发布可用 volatile；需要互斥或维护多字段不变量时使用锁，读多写少的一致配置可用不可变快照加 volatile 引用。",
      },
      {
        tag: "锁对象",
        question: "synchronized 到底锁什么？",
        answer: "锁对象监视器：实例同步方法锁 this，静态同步方法锁 Class，同步块锁表达式得到的对象。",
      },
      {
        tag: "发布",
        question: "什么叫安全发布？",
        answer: "其他线程既能看到引用，也被保证看到构造完成的合法状态；可通过静态初始化、volatile、同一锁或并发容器建立。",
      },
      {
        tag: "DCL",
        question: "双重检查锁为什么必须 volatile？",
        answer: "它安全发布构造完成的实例，并阻止读取者观察到引用已赋值而构造效果尚不可见的状态。",
      },
    ],
    finish:
      "能面对任意共享字段先问：它是独立发布、复合更新，还是多个字段共同维护不变量？",
  },
  {
    number: "03",
    stage: 1,
    title: "线程生命周期、中断与取消",
    shortTitle: "停止线程是一份合作协议",
    english: "LIFECYCLE & COOPERATIVE CANCELLATION",
    hook: "interrupt 不是 kill，它只是把请求送到正确的人手里。",
    lead:
      "从六种线程状态出发，追踪一个取消请求如何唤醒阻塞、恢复标志、离开循环、清理资源并最终被 join 验收。",
    outcome: "能实现不会吞掉中断、具有总超时和清理阶段的可取消任务。",
    accent: "amber",
    concepts: [
      {
        code: "I",
        title: "中断协议",
        subtitle: "cooperative request",
        body: "interrupt 设置目标线程中断状态；特定阻塞方法会抛 InterruptedException，让任务在安全点响应。",
        boundary: "不会自动回滚业务状态，也不保证线程立即结束。",
      },
      {
        code: "W",
        title: "条件等待",
        subtitle: "wait set",
        body: "wait 必须持有同一监视器并在 while 中反复检查条件；超时等待每次醒来都重算剩余预算。",
        boundary: "notifyAll 只让等待者重新竞争监视器，不代表条件仍成立。",
      },
      {
        code: "T",
        title: "线程本地作用域",
        subtitle: "ThreadLocal lifecycle",
        body: "ThreadLocal 是每线程一份变量；在线程池中必须在 finally 清理或恢复外层值。",
        boundary: "它不是跨线程上下文传播机制，线程复用会放大遗留数据风险。",
      },
    ],
    flowTitle: "一次正确的两阶段终止",
    flowLead:
      "取消请求从调用者流向 worker，中断标志可能在异常处被清除，因此需要恢复；终态再通过 latch/join 返回调用者。",
    flow: [
      {
        label: "任务运行",
        actor: "worker",
        action: "while (!isInterrupted)",
        before: "interrupt=false",
        after: "执行一个工作周期",
        detail: "任务在明确安全点观察停止协议，而不是被外部任意杀死。",
        signal: "RUNNABLE",
      },
      {
        label: "进入阻塞",
        actor: "worker",
        action: "sleep / wait / take",
        before: "RUNNABLE",
        after: "TIMED_WAITING / WAITING",
        detail: "阻塞方法负责高效等待，同时允许 interrupt 唤醒。",
        signal: "BLOCKING POINT",
      },
      {
        label: "发出请求",
        actor: "caller",
        action: "worker.interrupt()",
        before: "任务仍在阻塞",
        after: "InterruptedException",
        detail: "调用者只表达取消意图，任务仍负责业务一致性和清理。",
        signal: "CANCEL REQUEST",
      },
      {
        label: "恢复标志",
        actor: "worker catch",
        action: "currentThread().interrupt()",
        before: "异常已清除标志",
        after: "interrupt=true",
        detail: "当前层不能继续抛出时，恢复状态让循环或上层仍能观察取消。",
        signal: "PROTOCOL RESTORED",
      },
      {
        label: "清理资源",
        actor: "worker finally",
        action: "close + stopped.countDown",
        before: "循环退出",
        after: "资源关闭 / 终态可见",
        detail: "finally 是第二阶段，负责释放资源并发布已停止状态。",
        signal: "CLEANUP",
      },
      {
        label: "调用者验收",
        actor: "caller",
        action: "join(deadline)",
        before: "等待 worker 结束",
        after: "TERMINATED",
        detail: "join 既等待生命周期，也让 worker 的最终写对调用者可见。",
        signal: "TERMINAL STATE",
      },
    ],
    zones: [
      {
        code: "S",
        name: "Thread.State",
        kind: "JVM 生命周期状态",
        owner: "目标线程",
        value: "NEW → RUNNABLE → WAITING → TERMINATED",
        mutation: "由启动、阻塞、唤醒和结束驱动",
        rule: "状态需结合栈顶方法和锁信息解释。",
      },
      {
        code: "I",
        name: "interrupt flag",
        kind: "线程控制状态",
        owner: "每个 Thread",
        value: "false → true → exception clears → true",
        mutation: "interrupt / interrupted / 阻塞异常",
        rule: "不要空 catch，也不要无意清除。",
      },
      {
        code: "M",
        name: "wait set",
        kind: "监视器等待集合",
        owner: "GuardedMailbox monitor",
        value: "等待条件的线程节点",
        mutation: "wait 加入，notifyAll 唤醒竞争",
        rule: "条件与通知必须由同一监视器保护。",
      },
      {
        code: "TL",
        name: "requestId",
        kind: "ThreadLocal 槽位",
        owner: "线程池 worker",
        value: "请求 A → remove → 请求 B",
        mutation: "set / restore / remove",
        rule: "生命周期必须短于线程复用周期。",
      },
    ],
    routes: [
      {
        data: "取消意图",
        from: "服务关闭线程",
        via: "Thread.interrupt",
        to: "worker 中断状态",
        guarantee: "协作式通知，不是强杀",
      },
      {
        data: "阻塞唤醒",
        from: "中断状态",
        via: "InterruptedException",
        to: "任务 catch",
        guarantee: "异常通常清除标志",
      },
      {
        data: "停止终态",
        from: "worker finally",
        via: "CountDownLatch / join",
        to: "调用者",
        guarantee: "清理完成后再确认结束",
      },
      {
        data: "mailbox value",
        from: "producer",
        via: "同一 monitor + notifyAll",
        to: "waiting consumer",
        guarantee: "while 重检条件并共享总超时",
      },
    ],
    sourceKeys: ["03-termination", "03-mailbox", "03-exercise"],
    exercise: {
      title: "修复吞掉中断的任务",
      summary:
        "让 CancellationExercise 在收到 InterruptedException 后恢复中断、退出循环，并能被测试稳定验收。",
      requirements: [
        "catch 中恢复当前线程中断状态",
        "结束循环，不再继续生产工作单元",
        "说明异常为什么会清除中断标志",
        "扩展检查 finally 是否覆盖必要清理",
      ],
      testCommand: "mvn -Dtest=CancellationExerciseTest test",
      expected: "interrupt 后任务在限定时间内停止，中断语义没有丢失。",
    },
    runClass: "com.caesaemc.juc.lesson03.Lesson03Application",
    interview: [
      {
        tag: "协议",
        question: "interrupt 会立即停止线程吗？",
        answer: "不会。它设置状态或唤醒可中断阻塞，任务必须主动检查、传播异常或在安全点退出。",
      },
      {
        tag: "API",
        question: "interrupted 与 isInterrupted 有何区别？",
        answer: "Thread.interrupted 检查并清除当前线程状态；isInterrupted 检查目标线程且不清除。",
      },
      {
        tag: "异常",
        question: "为什么 catch InterruptedException 后常要恢复中断？",
        answer: "阻塞方法抛异常时通常已清除状态；不能继续抛出时恢复它，才能让上层或循环仍看到取消请求。",
      },
      {
        tag: "状态",
        question: "BLOCKED 与 WAITING 有何不同？",
        answer: "BLOCKED 专指等待 synchronized monitor；WAITING 是等待另一个线程动作，例如 wait、join 或 park。",
      },
      {
        tag: "线程池",
        question: "ThreadLocal 为什么会泄漏业务数据？",
        answer: "worker 长期存活并复用；任务不 remove 时，后续任务可能读取遗留值，关联对象生命周期也被延长。",
      },
    ],
    finish:
      "能画出 interrupt → 异常清标志 → 恢复 → 退出 → finally → join 的完整生命周期闭环。",
  },
  {
    number: "04",
    stage: 1,
    title: "CAS、原子类与高竞争计数",
    shortTitle: "无锁不等于无代价",
    english: "CAS / ABA / CONTENTION",
    hook: "一次 CAS 成功很快；一百万次失败重试未必。",
    lead:
      "把 CAS 看成带条件的原子提交：读取 observed、计算 next、比较并替换。再追踪 ABA 历史和 LongAdder 的分段数据分布。",
    outcome: "能解释原子更新的线性化点，并在强一致与高竞争指标之间做取舍。",
    accent: "green",
    concepts: [
      {
        code: "C",
        title: "CAS 提交",
        subtitle: "compare and set",
        body: "只有当前位置仍等于 observed 才原子写入 next；失败方重新读取并重算，成功动作是线性化点。",
        boundary: "高竞争下失败重试消耗 CPU，循环中的计算必须可安全重复。",
      },
      {
        code: "A",
        title: "ABA 历史",
        subtitle: "value + version",
        body: "值经历 A→B→A 后，普通 CAS 只看当前 A；带版本戳的 CAS 同时验证历史是否变化。",
        boundary: "只有中间变化具有业务意义时，ABA 才需要治理。",
      },
      {
        code: "L",
        title: "分段计数",
        subtitle: "LongAdder cells",
        body: "热点写入分散到 base 与多个 cell，读取时求和，降低所有线程竞争同一缓存位置。",
        boundary: "并发 sum 不是单点原子快照，不能用于余额、库存或序列号。",
      },
    ],
    flowTitle: "一次 CAS 扣款如何保持余额不为负",
    flowLead:
      "两个线程都可以计算候选值，但只有一个 compareAndSet 能基于同一个旧版本提交；失败者必须从共享状态重新开始。",
    flow: [
      {
        label: "读取余额",
        actor: "Thread A",
        action: "observed = balance.get()",
        before: "balance=100",
        after: "A observed=100",
        detail: "读取只是建立候选计算的基础，还没有保留余额。",
        signal: "OBSERVE",
      },
      {
        label: "并发读取",
        actor: "Thread B",
        action: "observed = balance.get()",
        before: "balance=100",
        after: "B observed=100",
        detail: "多个线程可以同时看到同一旧值，这是 CAS 的正常竞争前提。",
        signal: "CONTENTION",
      },
      {
        label: "计算候选",
        actor: "Thread A/B",
        action: "next = observed - 80",
        before: "两者 observed=100",
        after: "两者 next=20",
        detail: "先检查参数和余额不变量；外部不可重复调用不能放进重试计算。",
        signal: "PURE COMPUTE",
      },
      {
        label: "A 提交成功",
        actor: "Thread A",
        action: "CAS(100, 20)",
        before: "balance=100",
        after: "balance=20",
        detail: "原子比较替换成功，这一瞬间是 A 扣款的线性化点。",
        signal: "COMMIT",
      },
      {
        label: "B 提交失败",
        actor: "Thread B",
        action: "CAS(100, 20)",
        before: "balance 已是 20",
        after: "共享值不变",
        detail: "失败不是异常，只表示 observed 已过期；B 必须重新读取。",
        signal: "RETRY",
      },
      {
        label: "重新判定",
        actor: "Thread B",
        action: "20 < 80 → false",
        before: "observed=20",
        after: "扣款失败 / balance=20",
        detail: "余额不足在最新版本上被判断，不变量“余额不为负”得以保持。",
        signal: "INVARIANT",
      },
    ],
    zones: [
      {
        code: "H",
        name: "balance",
        kind: "共享原子整数",
        owner: "AtomicInteger",
        value: "100 → 20",
        mutation: "成功 CAS 才改变",
        rule: "检查和更新必须在同一重试循环。",
      },
      {
        code: "A",
        name: "observed / next",
        kind: "Thread A 局部变量",
        owner: "Thread A stack",
        value: "100 / 20",
        mutation: "每次重试重算",
        rule: "不能把局部候选当作已保留状态。",
      },
      {
        code: "B",
        name: "observed / next",
        kind: "Thread B 局部变量",
        owner: "Thread B stack",
        value: "100 → 20 / retry",
        mutation: "CAS 失败后失效",
        rule: "失败必须重新读取共享值。",
      },
      {
        code: "Σ",
        name: "LongAdder",
        kind: "分散共享计数",
        owner: "base + cells[]",
        value: "cell0 + cell1 + …",
        mutation: "线程分散写入",
        rule: "最终汇总适合指标，不提供并发原子快照。",
      },
    ],
    routes: [
      {
        data: "observed",
        from: "共享 balance",
        via: "volatile/atomic read",
        to: "线程局部",
        guarantee: "取得某一时刻的值",
      },
      {
        data: "next",
        from: "纯局部计算",
        via: "compareAndSet",
        to: "共享 balance",
        guarantee: "仅旧值仍匹配时提交",
      },
      {
        data: "ABA version",
        from: "AtomicStampedReference",
        via: "value + stamp CAS",
        to: "新引用与新版本",
        guarantee: "检测中间历史",
      },
      {
        data: "指标增量",
        from: "多个写线程",
        via: "base/cells 分段",
        to: "sum()",
        guarantee: "降低热点，读取为近似快照",
      },
    ],
    sourceKeys: ["04-cas", "04-aba", "04-exercise"],
    exercise: {
      title: "用 CAS 完成有界余额扣款",
      summary:
        "并发扣款不能让余额变负；只能通过成功 CAS 修改共享余额，并明确失败重试的边界。",
      requirements: [
        "amount 必须为正数",
        "每轮读取最新余额并检查是否足够",
        "CAS 失败后重新读取和计算",
        "指出成功 CAS 是线性化点",
      ],
      testCommand: "mvn -Dtest=BoundedBalanceExerciseTest test",
      expected: "任意并发交错下余额不为负，成功扣款总额与最终余额一致。",
    },
    runClass: "com.caesaemc.juc.lesson04.Lesson04Application",
    interview: [
      {
        tag: "原理",
        question: "CAS 是什么？",
        answer: "当前位置仍等于预期值时原子替换，否则失败；失败方通常重新读取并重试。",
      },
      {
        tag: "性能",
        question: "CAS 一定比锁快吗？",
        answer: "不一定。低竞争短操作常有优势，高竞争会产生大量重试和缓存一致性流量，队列化锁可能更合适。",
      },
      {
        tag: "ABA",
        question: "什么时候 ABA 是问题？",
        answer: "当 A→B→A 的中间历史影响业务语义时；可用版本戳、不复用节点或不可变状态引用解决。",
      },
      {
        tag: "选型",
        question: "AtomicLong 与 LongAdder 如何选？",
        answer: "需要强一致单值用 AtomicLong；高竞争统计且允许并发近似快照用 LongAdder。",
      },
      {
        tag: "底层",
        question: "VarHandle 与 Unsafe 有何关系？",
        answer: "VarHandle 是公开受支持的变量访问 API，提供不同内存模式和原子操作；业务代码不应依赖内部 Unsafe。",
      },
    ],
    finish:
      "能画出 observed → next → CAS → retry，并说明 AtomicLong 与 LongAdder 各自牺牲和保留了什么语义。",
  },
  {
    number: "05",
    stage: 2,
    title: "AQS、ReentrantLock 与 Condition",
    shortTitle: "唤醒不等于拿到锁",
    english: "AQS QUEUE & CONDITION TRANSFER",
    hook: "AQS 把“状态规则”和“排队机制”拆开了。",
    lead:
      "从 state 的一次失败获取出发，沿同步队列追踪入队、park、唤醒、重试；再观察 Condition 节点如何回到同步队列。",
    outcome: "能画出 AQS 获取/释放主线和 Condition 的双队列迁移。",
    accent: "cyan",
    concepts: [
      {
        code: "S",
        title: "state 语义",
        subtitle: "subclass contract",
        body: "AQS 子类定义什么状态表示获取或释放成功；同一个 state 可表达锁次数、剩余许可或剩余计数。",
        boundary: "AQS 不替子类决定业务状态含义，也不保证同步器一定可重入。",
      },
      {
        code: "Q",
        title: "同步等待队列",
        subtitle: "enqueue / park / retry",
        body: "tryAcquire 失败的线程进入 FIFO 思路的同步队列，检查前驱后 park，被唤醒时重新竞争。",
        boundary: "unpark 只提供再次尝试机会，不代表已经获得锁。",
      },
      {
        code: "C",
        title: "Condition 转移",
        subtitle: "condition → sync queue",
        body: "await 完全释放锁并进入条件队列；signal 把节点转入同步队列，重新获取锁后 await 才返回。",
        boundary: "等待必须用 while；signal 线程仍持有锁时，被通知线程无法继续。",
      },
    ],
    flowTitle: "一个 Condition 等待者如何重新进入临界区",
    flowLead:
      "跟随消费者从 notEmpty 条件不满足开始，直到生产者 signal 后再次获得同一把 ReentrantLock。",
    flow: [
      {
        label: "获得锁",
        actor: "consumer",
        action: "lockInterruptibly()",
        before: "同步队列外",
        after: "持有 lock",
        detail: "只有持锁线程才能检查由这把锁保护的 count 不变量。",
        signal: "EXCLUSIVE OWNER",
      },
      {
        label: "条件不满足",
        actor: "consumer",
        action: "count == 0",
        before: "count=0",
        after: "进入 notEmpty.await",
        detail: "条件检查位于 while 中，防止虚假唤醒和竞争后条件再次失效。",
        signal: "GUARD FALSE",
      },
      {
        label: "释放并等待",
        actor: "ConditionObject",
        action: "await()",
        before: "consumer 持锁",
        after: "条件队列节点 / 锁空闲",
        detail: "await 原子地加入条件队列并完全释放同步状态。",
        signal: "CONDITION QUEUE",
      },
      {
        label: "生产数据",
        actor: "producer",
        action: "put + count++",
        before: "count=0",
        after: "count=1",
        detail: "生产者持同一把锁修改数组、索引和 count，共同维护缓冲区不变量。",
        signal: "STATE CHANGE",
      },
      {
        label: "转移节点",
        actor: "producer",
        action: "notEmpty.signal()",
        before: "节点在条件队列",
        after: "节点进入同步队列",
        detail: "signal 不会立即交出锁，只把消费者送回重新竞争的路径。",
        signal: "QUEUE TRANSFER",
      },
      {
        label: "重新获得",
        actor: "consumer",
        action: "reacquire → take",
        before: "同步队列等待",
        after: "count=0 / 返回元素",
        detail: "消费者重新拿到锁、再次检查条件，取出元素并 signal notFull。",
        signal: "PROGRESS",
      },
    ],
    zones: [
      {
        code: "ST",
        name: "AQS state",
        kind: "volatile 共享整数",
        owner: "Sync 子类",
        value: "0 → 1 → 0",
        mutation: "CAS 获取 / setState 释放",
        rule: "具体含义由同步器定义。",
      },
      {
        code: "SQ",
        name: "sync queue",
        kind: "同步等待节点",
        owner: "AQS",
        value: "head → waiter → tail",
        mutation: "获取失败入队，释放唤醒",
        rule: "被唤醒后仍要 tryAcquire。",
      },
      {
        code: "CQ",
        name: "notEmpty",
        kind: "Condition 等待队列",
        owner: "BoundedBuffer",
        value: "等待消费者节点",
        mutation: "await 加入 / signal 转移",
        rule: "节点最终回到同步队列。",
      },
      {
        code: "B",
        name: "buffer state",
        kind: "锁保护共享数据",
        owner: "ReentrantLock",
        value: "elements + indexes + count",
        mutation: "put/take 临界区",
        rule: "多个字段共同维护容量不变量。",
      },
    ],
    routes: [
      {
        data: "获取请求",
        from: "调用线程",
        via: "tryAcquire",
        to: "成功或同步队列",
        guarantee: "失败时交给 AQS 排队",
      },
      {
        data: "释放信号",
        from: "当前 owner",
        via: "tryRelease + unpark",
        to: "合适后继",
        guarantee: "仅完全释放后传播",
      },
      {
        data: "条件节点",
        from: "Condition queue",
        via: "signal",
        to: "sync queue",
        guarantee: "重新竞争后 await 才返回",
      },
      {
        data: "buffer element",
        from: "producer",
        via: "同一 lock 临界区",
        to: "consumer",
        guarantee: "count/索引/数组原子维护",
      },
    ],
    sourceKeys: ["05-mutex", "05-condition", "05-exercise"],
    exercise: {
      title: "完成 AQS 共享模式一次性门闩",
      summary:
        "打开前所有线程等待，打开后已有和未来调用者都直接通过，并支持等待期间中断。",
      requirements: [
        "await 使用 acquireSharedInterruptibly",
        "open 使用 releaseShared 并传播唤醒",
        "state 只允许从 0 变为 1",
        "说明共享模式与 Mutex 独占模式的差异",
      ],
      testCommand: "mvn -Dtest=OneShotLatchExerciseTest test",
      expected: "打开前无线程越过门闩；一次 open 后全部及后续调用者通过。",
    },
    runClass: "com.caesaemc.juc.lesson05.Lesson05Application",
    interview: [
      {
        tag: "框架",
        question: "AQS 解决什么问题？",
        answer: "子类定义 state 获取释放规则，AQS 统一处理等待队列、阻塞、唤醒、中断和取消。",
      },
      {
        tag: "状态",
        question: "state 一定表示重入次数吗？",
        answer: "不一定。它可以表示重入次数、剩余许可、剩余计数或其他同步状态。",
      },
      {
        tag: "队列",
        question: "线程被 unpark 后是否已经获得锁？",
        answer: "没有。它只是恢复运行，仍需检查前驱并再次 tryAcquire，成功后才进入临界区。",
      },
      {
        tag: "公平",
        question: "公平锁是否绝对公平？",
        answer: "它减少插队并倾向等待顺序，但 JVM/OS 调度仍有差异，某些 tryLock 路径也有不同语义。",
      },
      {
        tag: "Condition",
        question: "signal 后等待线程为什么不能立即执行？",
        answer: "节点先从条件队列转到同步队列，signal 线程仍持锁；等待者重新获得锁后 await 才返回。",
      },
    ],
    finish:
      "能从 tryAcquire=false 开始画到入队、park、unpark、重试，并单独画出 Condition→同步队列的迁移。",
  },
  {
    number: "06",
    stage: 2,
    title: "同步工具与并发故障",
    shortTitle: "同步器表达业务生命周期",
    english: "SYNCHRONIZERS & FAILURE MODES",
    hook: "线程数量、资源许可和阶段参与者，是三种不同的容量。",
    lead:
      "用 Latch、Barrier、Semaphore 分别表达一次性完成、循环会合和稀缺资源；再把死锁、活锁、饥饿和锁竞争放进同一诊断坐标。",
    outcome: "能按生命周期选择同步器，并从等待关系识别并预防并发故障。",
    accent: "red",
    concepts: [
      {
        code: "L",
        title: "Latch / Barrier",
        subtitle: "completion vs rendezvous",
        body: "CountDownLatch 等待一次性计数归零；CyclicBarrier 让固定参与者互相等待并可进入下一代。",
        boundary: "Latch 不可重置；Barrier 的中断、超时或 action 失败会破坏当前代。",
      },
      {
        code: "S",
        title: "Semaphore",
        subtitle: "resource capacity",
        body: "许可表示数据库连接、外部 API 额度等真实稀缺资源；获取成功后必须在 finally 归还。",
        boundary: "它不负责线程复用、任务排队和执行器生命周期，不能简单替代线程池。",
      },
      {
        code: "F",
        title: "四类故障",
        subtitle: "deadlock / livelock / starvation / contention",
        body: "永久循环等待、持续动作无进展、长期得不到资源和高成本竞争，现象与治理方式各不相同。",
        boundary: "一次线程状态只是入口，必须结合持锁关系、堆栈、CPU 与持续时间。",
      },
    ],
    flowTitle: "一份资源许可如何覆盖正常与异常路径",
    flowLead:
      "许可只在成功 acquire 后属于当前调用；从进入 action 到离开 finally，每条出口都必须汇合到 release。",
    flow: [
      {
        label: "请求许可",
        actor: "caller",
        action: "permits.acquire()",
        before: "available=2",
        after: "等待或取得许可",
        detail: "等待的是资源容量，不是等待某个 worker 线程。",
        signal: "ADMISSION",
      },
      {
        label: "进入资源",
        actor: "ResourceGate",
        action: "active++",
        before: "available=2",
        after: "available=1 / active=1",
        detail: "只有 acquire 成功后才记录 active 并进入 try。",
        signal: "PERMIT OWNED",
      },
      {
        label: "执行业务",
        actor: "action",
        action: "call()",
        before: "许可由当前调用持有",
        after: "value 或 Throwable",
        detail: "正常返回、受检异常、运行时异常都只是不同出口。",
        signal: "WORK",
      },
      {
        label: "异常传播",
        actor: "call stack",
        action: "throw failure",
        before: "action 中断",
        after: "控制流进入 finally",
        detail: "异常不能绕过资源归还；也不能被伪装为“没有许可”。",
        signal: "FAILURE PATH",
      },
      {
        label: "归还许可",
        actor: "finally",
        action: "active-- / release",
        before: "当前调用拥有许可",
        after: "available=2 / active=0",
        detail: "正常和异常路径在 finally 汇合，容量恢复。",
        signal: "CAPACITY RESTORED",
      },
      {
        label: "诊断等待",
        actor: "observer",
        action: "dump + metrics",
        before: "大量线程等待",
        after: "区分许可等待/死锁/竞争",
        detail: "看谁持有什么、等什么、系统是否仍有进展，而不是只看线程数量。",
        signal: "EVIDENCE",
      },
    ],
    zones: [
      {
        code: "P",
        name: "permits",
        kind: "共享资源容量",
        owner: "Semaphore",
        value: "N → N-1 → N",
        mutation: "acquire / release",
        rule: "只对成功获取的许可执行一次释放。",
      },
      {
        code: "A",
        name: "active",
        kind: "运行指标",
        owner: "ResourceGate",
        value: "当前资源使用量",
        mutation: "进入/离开资源",
        rule: "maxObserved 不得超过许可总数。",
      },
      {
        code: "ST",
        name: "stamp",
        kind: "StampedLock 版本票据",
        owner: "每次读/写操作",
        value: "optimistic → validated",
        mutation: "写入会使旧票据失效",
        rule: "validate 失败必须在读锁下重读。",
      },
      {
        code: "D",
        name: "lock graph",
        kind: "持有/等待关系",
        owner: "ThreadMXBean / dump",
        value: "T1→L2 / T2→L1",
        mutation: "锁获取顺序形成",
        rule: "闭环表示死锁候选。",
      },
    ],
    routes: [
      {
        data: "许可",
        from: "Semaphore",
        via: "acquire",
        to: "调用作用域",
        guarantee: "最多 N 个同时进入",
      },
      {
        data: "许可",
        from: "调用作用域",
        via: "finally release",
        to: "Semaphore",
        guarantee: "异常路径不泄漏",
      },
      {
        data: "点坐标",
        from: "共享 x/y",
        via: "optimistic read + validate",
        to: "局部一致快照",
        guarantee: "失败时悲观锁重读",
      },
      {
        data: "锁关系",
        from: "JVM 线程",
        via: "ThreadMXBean / dump",
        to: "诊断者",
        guarantee: "展示持有者、等待者和栈",
      },
    ],
    sourceKeys: ["06-semaphore", "06-stamped", "06-exercise"],
    exercise: {
      title: "保证许可异常安全",
      summary:
        "修复 PermitGuardExercise，使 action 正常、受检异常或运行时异常时都恢复全部许可。",
      requirements: [
        "acquire 被中断时不能错误 release",
        "成功 acquire 后立即进入 try/finally",
        "finally 中只释放一次许可",
        "测试正常、异常和中断三类路径",
      ],
      testCommand: "mvn -Dtest=PermitGuardExerciseTest test",
      expected: "所有调用结束后 availablePermits 恢复初值，异常保持原始语义。",
    },
    runClass: "com.caesaemc.juc.lesson06.Lesson06Application",
    interview: [
      {
        tag: "选型",
        question: "CountDownLatch 与 CyclicBarrier 的本质区别？",
        answer: "Latch 等待一次性计数归零且不可重置；Barrier 让固定参与者互等并可循环进入下一代。",
      },
      {
        tag: "容量",
        question: "Semaphore 能替代线程池吗？",
        answer: "不能完全替代。Semaphore 限制资源并发；线程池还管理线程复用、任务排队、生命周期和拒绝。",
      },
      {
        tag: "StampedLock",
        question: "乐观读为什么必须 validate？",
        answer: "复制字段期间可能发生写入；验证失败必须在读锁下重读才能得到一致快照。",
      },
      {
        tag: "死锁",
        question: "死锁的四个必要条件是什么？",
        answer: "互斥、占有且等待、不可抢占、循环等待；常通过统一锁顺序、缩小持锁范围或超时获取预防。",
      },
      {
        tag: "诊断",
        question: "如何定位死锁？",
        answer: "查看 dump 中互相等待的锁、持有者和堆栈，或用 ThreadMXBean、jcmd Thread.print -l、jstack -l。",
      },
    ],
    finish:
      "能把“等初始化、每轮会合、限数据库并发、动态阶段”分别映射到正确同步器，并画出一张锁等待图。",
  },
  {
    number: "07",
    stage: 2,
    title: "ConcurrentHashMap 与并发集合",
    shortTitle: "方法安全不等于组合安全",
    english: "ATOMIC MAP OPERATIONS",
    hook: "containsKey 和 put 都安全，连在一起仍然可能错。",
    lead:
      "先用两个线程确定性复现重复加载，再把判断和建立收进 compute/merge 协议；同时理解弱一致迭代与扩容协作。",
    outcome: "能设计不存在 check-then-act 竞态，并明确缓存加载失败与重试语义。",
    accent: "green",
    concepts: [
      {
        code: "C",
        title: "复合原子操作",
        subtitle: "compute / merge",
        body: "容器的单方法线程安全不会自动覆盖跨方法不变量；应使用 compute、merge、putIfAbsent 等原子复合 API。",
        boundary: "映射函数应短小，不能递归更新同 key，也不宜持有内部更新路径执行慢远程调用。",
      },
      {
        code: "T",
        title: "桶级并发",
        subtitle: "CAS + bin synchronization",
        body: "空桶 CAS 安装首节点，冲突桶在更细粒度范围同步，扩容用 ForwardingNode 允许多线程协助迁移。",
        boundary: "现代 ConcurrentHashMap 不是早期 Segment 数组设计。",
      },
      {
        code: "W",
        title: "弱一致观察",
        subtitle: "not a global snapshot",
        body: "迭代和 size 可反映创建时或之后某些时刻的状态，不抛快速失败异常，也不保证瞬时全局快照。",
        boundary: "关键业务判断不能依赖并发更新期间的估计 size。",
      },
    ],
    flowTitle: "同一个 key 如何从两次加载变成一次原子建立",
    flowLead:
      "对比 check-then-act 的分离窗口与 computeIfAbsent 的同 key 原子计算边界。",
    flow: [
      {
        label: "同时检查",
        actor: "T1 + T2",
        action: "containsKey(key)",
        before: "map 为空",
        after: "两者都得到 false",
        detail: "每次 containsKey 都满足自身契约，但两次调用之间没有共同原子边界。",
        signal: "RACE WINDOW",
      },
      {
        label: "重复加载",
        actor: "T1 + T2",
        action: "load(key)",
        before: "两者都认为缺失",
        after: "creationCount=2",
        detail: "昂贵加载被执行两次，可能产生重复外部副作用。",
        signal: "DUPLICATE WORK",
      },
      {
        label: "覆盖写入",
        actor: "T1 + T2",
        action: "put(key, value)",
        before: "两个候选值",
        after: "map.size=1",
        detail: "最终只有一个映射不能证明加载只执行了一次。",
        signal: "LOST HISTORY",
      },
      {
        label: "原子计算",
        actor: "ConcurrentHashMap",
        action: "computeIfAbsent",
        before: "key 缺失",
        after: "建立同 key 计算边界",
        detail: "容器协调同 key 的判断和映射建立，其他调用者等待或观察结果。",
        signal: "ATOMIC COMPOUND",
      },
      {
        label: "发布结果",
        actor: "winning loader",
        action: "return value",
        before: "creationCount=0",
        after: "creationCount=1 / size=1",
        detail: "返回 null 不建立映射；抛异常也不会留下成功值。",
        signal: "MAPPING INSTALLED",
      },
      {
        label: "扩展为单飞",
        actor: "Memoizer",
        action: "map<K, Future<V>>",
        before: "远程加载很慢",
        after: "多个调用者共享在途 Future",
        detail: "需要超时、取消和失败重试时，Future 比长时间占用 compute 路径更清晰。",
        signal: "IN-FLIGHT VALUE",
      },
    ],
    zones: [
      {
        code: "T",
        name: "table[]",
        kind: "共享节点数组",
        owner: "ConcurrentHashMap",
        value: "空桶 / 链表 / 红黑树 / ForwardingNode",
        mutation: "CAS、桶级同步、协作迁移",
        rule: "不同桶可并发推进。",
      },
      {
        code: "K",
        name: "key mapping",
        kind: "同 key 原子域",
        owner: "computeIfAbsent",
        value: "absent → value",
        mutation: "映射函数成功返回",
        rule: "不要递归修改同 key。",
      },
      {
        code: "C",
        name: "count",
        kind: "分散计数状态",
        owner: "baseCount + counterCells",
        value: "估计映射数量",
        mutation: "并发增减",
        rule: "并发 size 不是事务快照。",
      },
      {
        code: "I",
        name: "iterator view",
        kind: "弱一致观察",
        owner: "迭代线程",
        value: "创建时或之后的部分元素",
        mutation: "不冻结 table",
        rule: "不抛 ConcurrentModificationException。",
      },
    ],
    routes: [
      {
        data: "key",
        from: "调用者",
        via: "hash → table bin",
        to: "桶节点",
        guarantee: "定位并发更新范围",
      },
      {
        data: "新 value",
        from: "mapping function",
        via: "computeIfAbsent",
        to: "key mapping",
        guarantee: "判断与建立原子组合",
      },
      {
        data: "迁移节点",
        from: "旧 table",
        via: "ForwardingNode",
        to: "新 table",
        guarantee: "多个线程可协助扩容",
      },
      {
        data: "元素视图",
        from: "变化中的 table",
        via: "弱一致 iterator",
        to: "观察线程",
        guarantee: "有进展但非全局瞬时快照",
      },
    ],
    sourceKeys: ["07-compound", "07-cache", "07-exercise"],
    exercise: {
      title: "把分离的缓存加载改成原子操作",
      summary:
        "让并发线程针对同一个 key 只执行一次成功加载，并回答 null、异常和递归更新的边界。",
      requirements: [
        "使用 computeIfAbsent 合并 get/load/put",
        "loader 不递归更新同一个 key",
        "解释 loader 返回 null 与抛异常的结果",
        "比较热点 key 下 merge<Long> 与 LongAdder",
      ],
      testCommand: "mvn -Dtest=CacheExerciseTest test",
      expected: "多个线程并发 get 同 key 时 loadCount 为 1，所有调用获得同一映射。",
    },
    runClass: "com.caesaemc.juc.lesson07.Lesson07Application",
    interview: [
      {
        tag: "实现",
        question: "ConcurrentHashMap 如何实现高并发？",
        answer: "读取通常无锁；空桶 CAS，冲突桶细粒度同步，扩容可协作迁移，计数用分散单元降低热点。",
      },
      {
        tag: "null",
        question: "为什么不允许 null key/value？",
        answer: "并发环境中 get==null 必须明确表示当前没有映射，不能再与“映射值是 null”混淆。",
      },
      {
        tag: "compute",
        question: "computeIfAbsent 的 loader 永远只调用一次吗？",
        answer: "不是永久一次。返回 null、抛异常、映射被移除或后续重算时仍会再次调用。",
      },
      {
        tag: "迭代",
        question: "并发迭代得到的是快照吗？",
        answer: "不是全局瞬时快照；它弱一致，不抛 ConcurrentModificationException，可看到创建时或之后的部分变化。",
      },
      {
        tag: "选型",
        question: "CopyOnWriteArrayList 适合什么场景？",
        answer: "集合小、读和遍历极多、写极少的监听器或路由表；频繁写或大数组会放大复制和内存成本。",
      },
    ],
    finish:
      "能看到任意 contains/get 后接 put 的代码就主动检查复合竞态，并说明 compute loader 的失败、阻塞和重试边界。",
  },
  {
    number: "08",
    stage: 2,
    title: "并发队列与生产消费",
    shortTitle: "队列容量就是系统承诺",
    english: "QUEUE SEMANTICS & BACKPRESSURE",
    hook: "无界队列没有消灭过载，只是把它推迟成内存和尾延迟。",
    lead:
      "用容量、顺序、移交和时间四个维度选择队列；观察元素如何从快速生产者经过有界缓冲流向消费者，再进入停止协议。",
    outcome: "能设计具有明确容量、满载行为、批处理和关闭语义的生产消费流水线。",
    accent: "amber",
    concepts: [
      {
        code: "B",
        title: "有界背压",
        subtitle: "capacity is policy",
        body: "ArrayBlockingQueue 在容量满时让 put 阻塞或 offer 失败，把过载显式传回生产者。",
        boundary: "无界队列会持续吸收任务，导致内存、排队时间和过期工作增长。",
      },
      {
        code: "H",
        title: "直接移交",
        subtitle: "SynchronousQueue",
        body: "容量为零，每次 put 必须与 take 配对；适合直接 handoff，不保存中间元素。",
        boundary: "生产和消费无法匹配时，调用会等待、超时或失败。",
      },
      {
        code: "T",
        title: "时间与批次",
        subtitle: "DelayQueue / take + drainTo",
        body: "延迟队列按到期时间释放头元素；批消费先 take 一个，再 drainTo 收集已到达元素。",
        boundary: "DelayQueue 是进程内内存结构，不是持久化分布式调度系统。",
      },
    ],
    flowTitle: "有界生产消费数据流",
    flowLead:
      "容量为 2 的队列把“输入已接受”和“仍在等待”变成可见状态，结束时每个消费者收到一个明确终止消息。",
    flow: [
      {
        label: "生产消息",
        actor: "producer",
        action: "new Message(input)",
        before: "输入在线程本地",
        after: "待提交消息",
        detail: "业务数据先封装成不可变消息，再交给共享队列。",
        signal: "PRODUCED",
      },
      {
        label: "进入队列",
        actor: "ArrayBlockingQueue",
        action: "put(message)",
        before: "size < capacity",
        after: "size + 1",
        detail: "队列既安全发布元素，也记录还未被处理的有限积压。",
        signal: "ENQUEUED",
      },
      {
        label: "容量满载",
        actor: "producer",
        action: "put waits",
        before: "size == capacity",
        after: "生产速率被限制",
        detail: "背压发生在接受新工作的位置，而不是让内存无限增长。",
        signal: "BACKPRESSURE",
      },
      {
        label: "消费取得",
        actor: "consumer",
        action: "take()",
        before: "队头有消息",
        after: "size - 1 / producer 可继续",
        detail: "take 在空队列时高效阻塞，在取得元素时建立队列定义的内存一致性。",
        signal: "DEQUEUED",
      },
      {
        label: "处理输出",
        actor: "consumer",
        action: "value × value",
        before: "消息为线程局部",
        after: "结果写入输出集合",
        detail: "耗时处理发生在队列锁外，避免阻塞其他生产与消费操作。",
        signal: "PROCESSED",
      },
      {
        label: "关闭流水线",
        actor: "producer",
        action: "N × poison pill",
        before: "业务消息已提交",
        after: "每个 consumer 退出",
        detail: "终止消息数量覆盖消费者数，done latch 确认所有消费线程结束。",
        signal: "DRAINED",
      },
    ],
    zones: [
      {
        code: "P",
        name: "input message",
        kind: "生产者局部数据",
        owner: "producer",
        value: "value + poison flag",
        mutation: "构造后不变",
        rule: "入队前尚未被消费者拥有。",
      },
      {
        code: "Q",
        name: "queue slots",
        kind: "有界共享缓冲",
        owner: "BlockingQueue",
        value: "0…capacity 个消息",
        mutation: "put/take",
        rule: "容量定义最大积压。",
      },
      {
        code: "C",
        name: "current message",
        kind: "消费者局部数据",
        owner: "consumer",
        value: "take 得到的单个元素",
        mutation: "处理后丢弃",
        rule: "耗时工作不占用队列内部锁。",
      },
      {
        code: "D",
        name: "done",
        kind: "生命周期计数",
        owner: "CountDownLatch",
        value: "consumerCount → 0",
        mutation: "每个消费者 finally countDown",
        rule: "调用者只在全部停止后返回。",
      },
    ],
    routes: [
      {
        data: "业务消息",
        from: "producer",
        via: "put / offer",
        to: "有界队列",
        guarantee: "按满载策略接受或反压",
      },
      {
        data: "队头消息",
        from: "BlockingQueue",
        via: "take",
        to: "consumer",
        guarantee: "空时阻塞，成功后安全交接",
      },
      {
        data: "批次",
        from: "队列",
        via: "take 1 + drainTo N-1",
        to: "batch list",
        guarantee: "不空转、不强等满批",
      },
      {
        data: "结束信号",
        from: "lifecycle owner",
        via: "poison pill × consumers",
        to: "每个 consumer",
        guarantee: "与合法业务消息明确区分",
      },
    ],
    sourceKeys: ["08-pipeline", "08-handoff", "08-exercise"],
    exercise: {
      title: "实现阻塞 + 非阻塞组合批消费",
      summary:
        "先 take 阻塞取得第一个元素，再 drainTo 补满当前批次，避免空转和等待不存在的完整批。",
      requirements: [
        "maxBatchSize <= 0 时拒绝",
        "使用 take() 取得第一个元素",
        "drainTo 最多 maxBatchSize - 1 个",
        "说明为何不能 while(queue.isEmpty()) 空转",
      ],
      testCommand: "mvn -Dtest=BatchingQueueExerciseTest test",
      expected: "空队列时阻塞；有数据后立即返回 1…maxBatchSize 个元素且不丢失。",
    },
    runClass: "com.caesaemc.juc.lesson08.Lesson08Application",
    interview: [
      {
        tag: "选型",
        question: "ArrayBlockingQueue 与 LinkedBlockingQueue 如何比较？",
        answer: "前者固定数组、容量明确、内存可预测；后者链表节点且应显式设容量，还要比较分配成本与锁结构。",
      },
      {
        tag: "移交",
        question: "SynchronousQueue 的容量是多少？",
        answer: "零。它不存元素，每次生产必须与消费直接配对。",
      },
      {
        tag: "风险",
        question: "无界队列有什么风险？",
        answer: "过载时任务持续积压，造成内存和尾延迟增长，也可能让最大线程等扩容机制失效。",
      },
      {
        tag: "停止",
        question: "如何优雅停止生产消费系统？",
        answer: "先停止生产，排空已接受任务，再中断或发送足量终止消息，并使用总超时和兜底取消。",
      },
      {
        tag: "延迟",
        question: "队列长度不高但 P99 等待很高，查什么？",
        answer: "记录入队到开始执行时间，检查队头长任务、优先级反转、突发流量与消费者暂停。",
      },
    ],
    finish:
      "能对任意队列先回答：容量多少、满时怎样、谁拥有元素、如何停止、排队时间如何观测。",
  },
  {
    number: "09",
    stage: 3,
    title: "ThreadPoolExecutor 原理",
    shortTitle: "四条提交路径决定过载行为",
    english: "EXECUTE DECISION MODEL",
    hook: "core、max、queue 不能拆开调，它们共同写出系统的饱和协议。",
    lead:
      "让一批阻塞任务依次走过核心线程、入队、非核心线程和拒绝，观察任务、Worker、队列与 ctl 如何协同。",
    outcome: "能完整推导 execute 的所有路径，并给出可观测、有界、拒绝明确的线程池。",
    accent: "cyan",
    concepts: [
      {
        code: "E",
        title: "execute 四路径",
        subtitle: "core → queue → max → reject",
        body: "worker 少于 core 先建核心线程；否则尝试入队；队列失败再扩到 max；仍失败则拒绝。",
        boundary: "任务入队后还要二次检查运行状态，处理与 shutdown 并发的窗口。",
      },
      {
        code: "C",
        title: "ctl 与 Worker",
        subtitle: "state + worker count",
        body: "ctl 原子编码运行状态和 worker 数；Worker 代表工作线程、首任务和任务获取循环。",
        boundary: "无需背位常量，但要理解状态与 workerCount 必须原子协调。",
      },
      {
        code: "R",
        title: "拒绝即背压",
        subtitle: "saturation contract",
        body: "Abort 明确失败，CallerRuns 降低提交速度，Discard 系列只有业务明确允许丢失时才能使用。",
        boundary: "拒绝不是异常兜底，而是容量设计和上游协议的一部分。",
      },
    ],
    flowTitle: "core=1、max=2、queue=1 的四次提交",
    flowLead:
      "所有任务都阻塞不结束，因此每次提交都能稳定看到线程池当前容量并走向唯一分支。",
    flow: [
      {
        label: "任务 1",
        actor: "execute",
        action: "workerCount < core",
        before: "workers=0 / queue=0",
        after: "core worker=1",
        detail: "线程池优先创建核心 Worker，并让它直接执行第一个任务。",
        signal: "START CORE",
      },
      {
        label: "任务 2",
        actor: "execute",
        action: "queue.offer",
        before: "workers=1 / queue=0",
        after: "workers=1 / queue=1",
        detail: "核心线程已满，运行状态正常且队列接受任务，因此暂不扩线程。",
        signal: "ENQUEUE",
      },
      {
        label: "二次检查",
        actor: "ThreadPoolExecutor",
        action: "recheck runState",
        before: "任务已在队列",
        after: "保留或移除并拒绝",
        detail: "防止 offer 与 shutdown 并发导致已停止线程池留下无人处理的任务。",
        signal: "STATE RECHECK",
      },
      {
        label: "任务 3",
        actor: "execute",
        action: "queue full → addWorker",
        before: "workers=1 / queue=1",
        after: "non-core worker=2",
        detail: "有界队列给出明确满载信号，线程数才继续扩到 maximum。",
        signal: "START NON-CORE",
      },
      {
        label: "任务 4",
        actor: "execute",
        action: "addWorker fails",
        before: "workers=max / queue=full",
        after: "RejectedExecutionException",
        detail: "系统容量已耗尽，拒绝策略把过载传回调用方。",
        signal: "REJECT",
      },
      {
        label: "释放与收集",
        actor: "workers",
        action: "getTask loop",
        before: "阻塞任务被放行",
        after: "queue 清空 / completed++",
        detail: "Worker 完成当前任务后从队列取下一个，钩子和指标记录执行生命周期。",
        signal: "DRAIN",
      },
    ],
    zones: [
      {
        code: "CTL",
        name: "ctl",
        kind: "原子控制字",
        owner: "ThreadPoolExecutor",
        value: "runState + workerCount",
        mutation: "启动、关闭、Worker 增减",
        rule: "相关状态转换原子协调。",
      },
      {
        code: "W",
        name: "Worker set",
        kind: "受锁保护线程集合",
        owner: "线程池",
        value: "0…maximumPoolSize",
        mutation: "addWorker / processWorkerExit",
        rule: "Worker 承载首任务与 getTask 循环。",
      },
      {
        code: "Q",
        name: "workQueue",
        kind: "任务缓冲区",
        owner: "BlockingQueue",
        value: "0…capacity",
        mutation: "offer / take",
        rule: "队列类型决定何时扩到 max。",
      },
      {
        code: "M",
        name: "metrics",
        kind: "运行观测数据",
        owner: "InstrumentedThreadPool",
        value: "submitted/active/queued/rejected",
        mutation: "提交、钩子、拒绝处理器",
        rule: "还需观测排队与执行时间分布。",
      },
    ],
    routes: [
      {
        data: "Runnable",
        from: "submitter",
        via: "execute decision",
        to: "core Worker / queue / non-core / rejection",
        guarantee: "四条互斥路径",
      },
      {
        data: "queued task",
        from: "workQueue",
        via: "Worker.getTask",
        to: "runWorker",
        guarantee: "Worker 循环消费",
      },
      {
        data: "failure",
        from: "task.run",
        via: "execute 或 FutureTask",
        to: "异常处理器或 Future",
        guarantee: "submit 失败需显式 get/检查",
      },
      {
        data: "saturation",
        from: "max + full queue",
        via: "RejectedExecutionHandler",
        to: "上游限流/降级",
        guarantee: "禁止静默过载",
      },
    ],
    sourceKeys: ["09-decision", "09-saturation", "09-exercise"],
    exercise: {
      title: "创建显式有界线程池",
      summary:
        "不用隐藏无界队列的便捷工厂，直接定义 core、max、容量、线程命名和拒绝策略。",
      requirements: [
        "直接构造 ThreadPoolExecutor",
        "使用明确容量的 ArrayBlockingQueue",
        "ThreadFactory 包含业务前缀",
        "选择并解释拒绝策略及 core/max/queue 联动",
      ],
      testCommand: "mvn -Dtest=PoolConfigExerciseTest test",
      expected: "线程名称、队列容量和饱和拒绝均可从测试中直接观察。",
    },
    runClass: "com.caesaemc.juc.lesson09.Lesson09Application",
    interview: [
      {
        tag: "主线",
        question: "ThreadPoolExecutor 的提交顺序？",
        answer: "先核心线程，再入队；队列失败后再创建到最大线程数，最后拒绝。",
      },
      {
        tag: "队列",
        question: "为什么无界队列会让 max 基本失效？",
        answer: "达到 core 后任务持续成功入队，只有 offer 失败才会扩到 max，而无界队列通常不失败。",
      },
      {
        tag: "源码",
        question: "ctl 有什么作用？",
        answer: "一个原子字段同时编码线程池运行状态与 worker 数，使两者的相关转换可以原子协调。",
      },
      {
        tag: "异常",
        question: "execute 与 submit 的异常表现有何不同？",
        answer: "execute 的未捕获异常通常到达 worker 异常处理；submit 包装 FutureTask，异常存入 Future。",
      },
      {
        tag: "背压",
        question: "CallerRunsPolicy 的意义和风险？",
        answer: "由提交线程执行以减慢提交形成反压，但会占用请求/事件循环线程，还需防递归提交。",
      },
    ],
    finish:
      "给定任意 core/max/queue 与一组阻塞任务，能逐个推导提交路径、线程数、队列长度和拒绝结果。",
  },
  {
    number: "10",
    stage: 3,
    title: "线程池工程实践、Future 与调度",
    shortTitle: "超时只结束等待，不自动结束工作",
    english: "FUTURE STATE & SHUTDOWN",
    hook: "任务完成、调用者放弃和线程真正停止，是三个不同事件。",
    lead:
      "沿 FutureTask 状态机追踪成功、失败、超时与取消，再执行 shutdown→await→shutdownNow 的两阶段关闭。",
    outcome: "能设计有总 deadline、异常可见、任务可取消且能优雅关闭的执行器。",
    accent: "red",
    concepts: [
      {
        code: "F",
        title: "Future 终态",
        subtitle: "result / failure / cancellation",
        body: "FutureTask 用状态与 outcome 保存正常结果或异常，get 在未完成时等待，完成后唤醒所有等待者。",
        boundary: "submit 的异常不会自动出现在 UncaughtExceptionHandler，必须 get 或在钩子中检查。",
      },
      {
        code: "D",
        title: "deadline 与 cancel",
        subtitle: "stop waiting ≠ stop work",
        body: "get(timeout) 超时后调用者应决定是否 cancel(true)；中断只是请求，任务和底层客户端必须合作。",
        boundary: "每次重置固定 timeout 会让整组等待时间累加。",
      },
      {
        code: "S",
        title: "执行器关闭",
        subtitle: "drain then force",
        body: "shutdown 停止接收，await 等待已接收任务；预算耗尽后 shutdownNow 中断并返回未开始任务。",
        boundary: "shutdownNow 也不承诺立即终止，捕获中断后要恢复调用者状态。",
      },
    ],
    flowTitle: "一个任务从提交到超时取消",
    flowLead:
      "把 Future 状态与真实 runner 分开观察：Future 可以进入取消终态，而底层任务仍需要响应中断才能释放资源。",
    flow: [
      {
        label: "包装提交",
        actor: "ExecutorService",
        action: "submit(Callable)",
        before: "普通 Callable",
        after: "FutureTask state=NEW",
        detail: "submit 把任务、结果槽位和等待机制包装到 FutureTask。",
        signal: "NEW",
      },
      {
        label: "占用 runner",
        actor: "worker",
        action: "FutureTask.run",
        before: "runner=null",
        after: "runner=worker",
        detail: "CAS 保证同一个 FutureTask 的 call 只由一个 runner 执行。",
        signal: "RUNNING",
      },
      {
        label: "调用者等待",
        actor: "caller",
        action: "get(remaining)",
        before: "state=NEW",
        after: "进入等待节点",
        detail: "剩余时间来自整组共享 deadline，而不是每个 Future 重置完整时长。",
        signal: "WAITING",
      },
      {
        label: "预算耗尽",
        actor: "caller",
        action: "TimeoutException",
        before: "Future 未完成",
        after: "调用者停止等待",
        detail: "这一刻还没有证明任务停止，只说明等待协议已到期。",
        signal: "TIMED OUT",
      },
      {
        label: "请求取消",
        actor: "FutureTask",
        action: "cancel(true)",
        before: "runner 仍执行",
        after: "INTERRUPTING → INTERRUPTED",
        detail: "Future 进入取消终态，并尝试中断 runner；任务代码仍需配合。",
        signal: "CANCEL REQUESTED",
      },
      {
        label: "关闭执行器",
        actor: "lifecycle owner",
        action: "shutdown / await / shutdownNow",
        before: "服务准备退出",
        after: "终止或报告未开始任务",
        detail: "关闭使用同一总预算，最终保留 forced 与 neverStarted 证据。",
        signal: "TERMINATION",
      },
    ],
    zones: [
      {
        code: "ST",
        name: "FutureTask state",
        kind: "原子状态机",
        owner: "FutureTask",
        value: "NEW → NORMAL / EXCEPTIONAL / CANCELLED",
        mutation: "run、set、setException、cancel",
        rule: "终态只完成一次。",
      },
      {
        code: "O",
        name: "outcome",
        kind: "结果槽位",
        owner: "FutureTask",
        value: "value 或 Throwable",
        mutation: "完成阶段写入",
        rule: "get 根据终态返回或包装异常。",
      },
      {
        code: "R",
        name: "runner",
        kind: "执行线程引用",
        owner: "FutureTask",
        value: "null → worker → null",
        mutation: "run CAS / finishCompletion",
        rule: "cancel(true) 只能请求中断当前 runner。",
      },
      {
        code: "Q",
        name: "executor queue",
        kind: "未开始任务集合",
        owner: "ExecutorService",
        value: "queued Runnable/FutureTask",
        mutation: "submit / Worker take / shutdownNow drain",
        rule: "强制关闭返回未开始任务。",
      },
    ],
    routes: [
      {
        data: "Callable",
        from: "caller",
        via: "submit",
        to: "FutureTask + queue",
        guarantee: "结果与失败有承载对象",
      },
      {
        data: "Throwable",
        from: "task",
        via: "Future outcome",
        to: "get → ExecutionException.cause",
        guarantee: "失败不会自动打印",
      },
      {
        data: "取消请求",
        from: "timeout caller",
        via: "cancel(true) / interrupt",
        to: "runner",
        guarantee: "协作式，不保证远端停止",
      },
      {
        data: "关闭信号",
        from: "lifecycle owner",
        via: "shutdown / shutdownNow",
        to: "queue + workers",
        guarantee: "先排空，后强制",
      },
    ],
    sourceKeys: ["10-deadline", "10-shutdown", "10-exercise"],
    exercise: {
      title: "实现具有总超时的两阶段关闭",
      summary:
        "停止接收新任务，等待已接受任务；预算耗尽后中断并再次等待，中断当前线程时保留协议。",
      requirements: [
        "先调用 shutdown",
        "根据同一 deadline 计算 await 剩余时间",
        "超时后调用 shutdownNow 并再次等待",
        "捕获 InterruptedException 后 shutdownNow 且恢复中断",
      ],
      testCommand: "mvn -Dtest=ShutdownExerciseTest test",
      expected: "正常任务排空，卡住任务进入强制阶段，中断调用者的状态得到恢复。",
    },
    runClass: "com.caesaemc.juc.lesson10.Lesson10Application",
    interview: [
      {
        tag: "异常",
        question: "execute 和 submit 的异常区别？",
        answer: "execute 的未捕获异常通常到达 worker 异常处理；submit 用 FutureTask 保存异常，需要 get 或显式检查。",
      },
      {
        tag: "取消",
        question: "Future.cancel(true) 一定停止任务吗？",
        answer: "不一定。它请求中断 runner；任务忽略中断或卡在不可中断操作时仍可能继续。",
      },
      {
        tag: "关闭",
        question: "shutdown 与 shutdownNow 的差别？",
        answer: "前者停止接收但处理已提交任务；后者尝试中断运行任务并返回未开始任务，都不承诺立即终止。",
      },
      {
        tag: "调度",
        question: "fixed-rate 与 fixed-delay？",
        answer: "fixed-rate 按计划开始时间推进；fixed-delay 从上一次结束后再等待固定延迟。",
      },
      {
        tag: "周期任务",
        question: "周期任务抛出未处理异常后会怎样？",
        answer: "后续执行会被抑制，因此任务内部必须记录异常并明确是否继续的策略。",
      },
    ],
    finish:
      "能把 Future 的终态、runner 的真实状态和调用者的 deadline 分成三条线说明，并写出可靠关闭顺序。",
  },
  {
    number: "11",
    stage: 3,
    title: "CompletableFuture 异步编排",
    shortTitle: "把异步代码画成完成图",
    english: "COMPLETION GRAPH",
    hook: "thenCompose 是依赖边，thenCombine 是汇合点，异常也是图中的数据。",
    lead:
      "将多下游调用建模为有向完成图：独立节点并行、依赖节点展平、结果节点汇合，每个来源先转为稳定 Outcome。",
    outcome: "能构建执行器明确、异常不丢失、允许部分结果且具有整体 deadline 的异步流程。",
    accent: "green",
    concepts: [
      {
        code: "→",
        title: "依赖展开",
        subtitle: "thenApply vs thenCompose",
        body: "普通值转换用 thenApply；函数返回 CompletionStage 时用 thenCompose 展平，表达后一调用依赖前一结果。",
        boundary: "错误使用 thenApply 会得到 CompletableFuture<CompletableFuture<T>>。",
      },
      {
        code: "＋",
        title: "独立汇合",
        subtitle: "thenCombine / allOf",
        body: "独立任务先并行启动，再用 thenCombine 汇合两个结果；allOf 协调全部完成但自身只返回 Void。",
        boundary: "必须保留原始 Future 才能按类型和输入顺序收集结果。",
      },
      {
        code: "!",
        title: "异常也是结果",
        subtitle: "handle / exceptionally / whenComplete",
        body: "handle 同时转换成功失败，exceptionally 只恢复失败，whenComplete 主要观察并保留原结果语义。",
        boundary: "取消 CompletableFuture 不能被当作可靠中断任意底层任务。",
      },
    ],
    flowTitle: "三个下游如何保留部分结果",
    flowLead:
      "每个来源拥有自己的 Future 和超时边，先转换成 Outcome；allOf 只等待节点，最终按输入顺序收集。",
    flow: [
      {
        label: "建立来源图",
        actor: "aggregator",
        action: "sources.forEach",
        before: "name → Supplier",
        after: "name → Future<Outcome>",
        detail: "LinkedHashMap 同时保留来源身份和稳定输出顺序。",
        signal: "GRAPH BUILT",
      },
      {
        label: "并行启动",
        actor: "custom executor",
        action: "supplyAsync",
        before: "3 个独立 Supplier",
        after: "3 个并行 stage",
        detail: "显式执行器避免无意占用 commonPool，并便于按下游隔离。",
        signal: "FAN OUT",
      },
      {
        label: "设置时间边",
        actor: "each stage",
        action: "orTimeout",
        before: "任务仍可能运行",
        after: "stage 可异常完成",
        detail: "阶段超时只改变完成图；底层请求取消还需要执行层能力。",
        signal: "TIME BOUNDARY",
      },
      {
        label: "归一化结果",
        actor: "handle",
        action: "value/failure → Outcome",
        before: "成功或包装异常",
        after: "稳定 Outcome",
        detail: "一个来源失败不再短路并丢掉其他成功来源。",
        signal: "NORMALIZED",
      },
      {
        label: "等待汇合",
        actor: "allOf",
        action: "wait all nodes",
        before: "部分 stage 完成",
        after: "Void completion",
        detail: "allOf 只表示完成屏障，具体结果仍存在各自 Future 中。",
        signal: "JOIN",
      },
      {
        label: "有序收集",
        actor: "thenApply",
        action: "future.join()",
        before: "所有 Future 已完成",
        after: "List<Outcome>",
        detail: "成功、失败、超时按来源保留，上层再决定关键失败或降级。",
        signal: "FAN IN",
      },
    ],
    zones: [
      {
        code: "G",
        name: "stage graph",
        kind: "完成依赖关系",
        owner: "CompletableFuture",
        value: "fan-out → handle → allOf → collect",
        mutation: "上游完成触发下游",
        rule: "依赖与独立关系必须真实建模。",
      },
      {
        code: "E",
        name: "executor",
        kind: "执行资源",
        owner: "业务组件",
        value: "blocking / CPU / critical pools",
        mutation: "Async stage 提交",
        rule: "不默认混用 commonPool。",
      },
      {
        code: "O",
        name: "Outcome",
        kind: "稳定结果数据",
        owner: "每个来源",
        value: "value 或 failure",
        mutation: "handle 完成时一次形成",
        rule: "部分成功不被单点失败抹掉。",
      },
      {
        code: "CTX",
        name: "request context",
        kind: "显式上下文",
        owner: "调用参数",
        value: "requestId / deadline",
        mutation: "沿函数参数传递",
        rule: "ThreadLocal 不自动跨任意执行器传播。",
      },
    ],
    routes: [
      {
        data: "user id",
        from: "入口",
        via: "thenCompose",
        to: "依赖详情调用",
        guarantee: "展平一条依赖链",
      },
      {
        data: "profile + preference",
        from: "两个独立 Future",
        via: "thenCombine",
        to: "组合结果",
        guarantee: "并行后汇合",
      },
      {
        data: "Throwable",
        from: "任一来源",
        via: "handle + unwrap",
        to: "Outcome.failure",
        guarantee: "异常成为显式数据",
      },
      {
        data: "所有 Outcome",
        from: "原始 Future map",
        via: "allOf completion",
        to: "ordered list",
        guarantee: "顺序稳定、类型保留",
      },
    ],
    sourceKeys: ["11-aggregate", "11-composition", "11-exercise"],
    exercise: {
      title: "展平依赖异步调用",
      summary:
        "把用户加载后再查详情的嵌套 Future 改为单层完成图，并解释 compose 与 combine 的关系。",
      requirements: [
        "loadFlat 返回 CompletableFuture<String>",
        "使用 thenCompose 展平依赖调用",
        "不为虚假并行破坏真实数据依赖",
        "扩展聚合时保留整体 deadline 与来源 Outcome",
      ],
      testCommand: "mvn -Dtest=CompositionExerciseTest test",
      expected: "返回单层 Future，异常和完成状态沿同一依赖图传播。",
    },
    runClass: "com.caesaemc.juc.lesson11.Lesson11Application",
    interview: [
      {
        tag: "组合",
        question: "thenApply 与 thenCompose？",
        answer: "apply 把值映射为值；compose 用于返回 CompletionStage 的函数并展平嵌套。",
      },
      {
        tag: "关系",
        question: "thenCombine 与 thenCompose？",
        answer: "combine 汇合两个相互独立阶段；compose 表达后续异步阶段依赖前一结果。",
      },
      {
        tag: "线程",
        question: "不带 Async 的 continuation 在哪个线程执行？",
        answer: "可能由完成上游的线程执行；上游已完成时也可能由注册动作的线程执行，不能假设固定线程。",
      },
      {
        tag: "allOf",
        question: "allOf 如何取得类型化结果？",
        answer: "保留原始 Future 列表或映射，allOf 完成后逐个 join/get；allOf 自身只返回 Void。",
      },
      {
        tag: "取消",
        question: "CompletableFuture.cancel(true) 会可靠中断任务吗？",
        answer: "不能这样假定。需要在实际执行器、网络调用和任务代码层设计取消。",
      },
    ],
    finish:
      "能把任意异步链画成节点和边，并逐条标注依赖、执行器、异常、超时、取消与最终收集位置。",
  },
  {
    number: "12",
    stage: 3,
    title: "ForkJoinPool 与任务模型选型",
    shortTitle: "让空闲 Worker 去偷可分割的工作",
    english: "WORK STEALING & TASK SHAPING",
    hook: "并行不是多开几个线程，而是把工作切成适合调度的形状。",
    lead:
      "跟随一个数组区间递归拆分，观察本地双端队列、工作窃取和 fork/compute/join；再把阻塞与 commonPool 风险纳入选型。",
    outcome: "能为分治计算选择阈值，并在 ForkJoin、CF、平台池和虚拟线程间正确选型。",
    accent: "amber",
    concepts: [
      {
        code: "W",
        title: "工作窃取",
        subtitle: "local deque",
        body: "每个 worker 优先处理本地任务，空闲时从其他 worker 队列窃取，降低集中队列竞争并平衡工作。",
        boundary: "子任务极不均、过小或长时间阻塞都会削弱收益。",
      },
      {
        code: "F",
        title: "fork/compute/join",
        subtitle: "one fork, one inline",
        body: "拆为左右任务，fork 一个分支，当前线程直接 compute 另一个，再 join 合并。",
        boundary: "阈值必须用真实数据和 JMH 测量，不能机械照搬。",
      },
      {
        code: "B",
        title: "阻塞补偿",
        subtitle: "ManagedBlocker",
        body: "不可避免阻塞时，ManagedBlocker 告诉池当前 worker 可能不可用，使其评估补偿。",
        boundary: "它不会把 I/O 变快，也不替代超时、取消和资源限流。",
      },
    ],
    flowTitle: "一个数组如何被拆成可窃取任务",
    flowLead:
      "从 [0, N) 区间开始，阈值决定顺序叶子；当前 Worker 保留一个分支继续算，把另一个暴露给其他 Worker。",
    flow: [
      {
        label: "接收区间",
        actor: "Worker 0",
        action: "compute[0,N)",
        before: "一个大任务",
        after: "检查 N <= threshold",
        detail: "任务只保存数组引用与 start/end，不复制数据。",
        signal: "TASK",
      },
      {
        label: "二分任务",
        actor: "Worker 0",
        action: "middle=(start+end)>>>1",
        before: "[0,N)",
        after: "left + right",
        detail: "拆分让两个子区间互不覆盖，合并函数保持可结合。",
        signal: "SPLIT",
      },
      {
        label: "暴露左支",
        actor: "Worker 0 deque",
        action: "left.fork()",
        before: "left 尚未调度",
        after: "left 可被窃取",
        detail: "fork 把任务放入当前 worker 的本地队列，空闲 worker 可从另一端获取。",
        signal: "FORK",
      },
      {
        label: "直算右支",
        actor: "Worker 0",
        action: "right.compute()",
        before: "当前线程可运行",
        after: "rightResult",
        detail: "不把两个分支都入队，当前 worker 继续做有用工作。",
        signal: "INLINE COMPUTE",
      },
      {
        label: "窃取左支",
        actor: "Worker 1",
        action: "steal left",
        before: "Worker 1 空闲",
        after: "并行计算 left",
        detail: "工作窃取按需求发生，不需要所有线程争抢同一个中央队列。",
        signal: "STEAL",
      },
      {
        label: "合并结果",
        actor: "Worker 0",
        action: "left.join + right",
        before: "两个子结果",
        after: "父任务结果",
        detail: "join 等待或直接取得已完成结果，递归向上归约到最终值。",
        signal: "REDUCE",
      },
    ],
    zones: [
      {
        code: "A",
        name: "values[]",
        kind: "共享只读数组",
        owner: "所有 RecursiveTask",
        value: "同一底层数据",
        mutation: "不修改",
        rule: "子任务只持有不重叠区间。",
      },
      {
        code: "D0",
        name: "Worker 0 deque",
        kind: "本地任务双端队列",
        owner: "ForkJoin worker 0",
        value: "本地 fork 的任务",
        mutation: "owner push/pop，其他 worker steal",
        rule: "降低集中竞争。",
      },
      {
        code: "D1",
        name: "Worker 1 deque",
        kind: "本地任务双端队列",
        owner: "ForkJoin worker 1",
        value: "本地或窃取任务",
        mutation: "计算完成后变空",
        rule: "空闲时从其他队列窃取。",
      },
      {
        code: "CP",
        name: "commonPool",
        kind: "进程共享执行资源",
        owner: "多个组件",
        value: "parallelStream / Async task",
        mutation: "全局提交与阻塞",
        rule: "无隔离时一个组件会影响其他组件。",
      },
    ],
    routes: [
      {
        data: "区间任务",
        from: "父 RecursiveTask",
        via: "fork",
        to: "本地 deque",
        guarantee: "可被其他 worker 获取",
      },
      {
        data: "窃取任务",
        from: "Worker 0 deque",
        via: "steal",
        to: "Worker 1",
        guarantee: "空闲算力参与",
      },
      {
        data: "子结果",
        from: "left/right compute",
        via: "join + reduce",
        to: "父任务",
        guarantee: "递归归约",
      },
      {
        data: "阻塞信息",
        from: "ManagedBlocker",
        via: "managedBlock",
        to: "ForkJoinPool",
        guarantee: "允许池评估补偿",
      },
    ],
    sourceKeys: ["12-forkjoin", "12-blocker", "12-exercise"],
    exercise: {
      title: "实现并行最大值 RecursiveTask",
      summary:
        "小区间顺序求最大值，大区间拆分，fork 一个分支、当前线程计算另一个，再 join 合并。",
      requirements: [
        "空数组必须拒绝",
        "小于阈值时顺序扫描",
        "大任务拆为两个不重叠区间",
        "fork/compute/join 后取两个结果最大值",
      ],
      testCommand: "mvn -Dtest=MaxTaskExerciseTest test",
      expected: "不同长度与阈值下结果等于顺序最大值，任务不会访问越界。",
    },
    runClass: "com.caesaemc.juc.lesson12.Lesson12Application",
    interview: [
      {
        tag: "原理",
        question: "什么是工作窃取？",
        answer: "每个 worker 维护本地队列，空闲 worker 从其他队列窃取任务，降低集中竞争并改善负载均衡。",
      },
      {
        tag: "任务",
        question: "RecursiveTask 与 RecursiveAction？",
        answer: "RecursiveTask 有返回值，RecursiveAction 没有返回值。",
      },
      {
        tag: "模式",
        question: "为什么 fork 一个、直接 compute 一个？",
        answer: "当前 worker 继续做有用工作，减少两个分支都入队再等待的额外调度。",
      },
      {
        tag: "阻塞",
        question: "ForkJoinPool 适合阻塞任务吗？",
        answer: "主要面向计算任务；不可避免阻塞可考虑 ManagedBlocker，大量阻塞通常更适合虚拟线程或隔离平台池。",
      },
      {
        tag: "风险",
        question: "parallelStream 为什么在线上可能有问题？",
        answer: "默认共享 commonPool，阻塞和重任务会影响其他组件，并行成本也可能高于顺序收益。",
      },
    ],
    finish:
      "能为一个任务说明数据是否可分、子任务是否均衡、阈值如何测、是否阻塞，以及为什么选择或拒绝 ForkJoin。",
  },
  {
    number: "13",
    stage: 3,
    title: "虚拟线程与结构化并发",
    shortTitle: "任务载体便宜，外部资源仍然昂贵",
    english: "VIRTUAL THREADS & RESOURCE LIMITS",
    hook: "不要建一个“20 线程的虚拟线程池”来假装数据库只有 20 个连接。",
    lead:
      "把每个阻塞任务放到独立虚拟线程上，再用 Semaphore 单独表达真实下游容量；沿 carrier 卸载、pinning 和父子生命周期理解边界。",
    outcome: "能判断迁移虚拟线程的收益，并保留资源限流、deadline、取消和可观测性。",
    accent: "green",
    concepts: [
      {
        code: "V",
        title: "每任务一线程",
        subtitle: "cheap Thread, direct style",
        body: "虚拟线程由 JVM 调度，支持的阻塞点通常可卸载 carrier，让平台线程运行其他虚拟线程。",
        boundary: "不会增加 CPU 核心，也不会让 CPU 密集任务获得超额并行。",
      },
      {
        code: "R",
        title: "资源容量分离",
        subtitle: "threads ≠ connections",
        body: "虚拟线程承载任务数量，Semaphore、连接池或下游额度单独限制真实资源并发。",
        boundary: "迁移后若没有显式 Bulkhead，廉价在途任务可能瞬间打满数据库。",
      },
      {
        code: "S",
        title: "结构化生命周期",
        subtitle: "parent owns children",
        body: "父作用域 fork 子任务、join/截止、按策略处理失败，离开作用域前确保子任务结束。",
        boundary: "JDK 21 的 StructuredTaskScope/ScopedValue 为预览 API，需按目标 JDK 调整。",
      },
    ],
    flowTitle: "1,000 个任务如何经过 20 个资源许可",
    flowLead:
      "任务可以各自拥有虚拟线程，但只有取得许可的 20 个任务进入外部资源；其余线程廉价等待并受 deadline 约束。",
    flow: [
      {
        label: "创建任务载体",
        actor: "virtual executor",
        action: "submit each call",
        before: "1,000 个 Callable",
        after: "1,000 个虚拟线程",
        detail: "不先把任务塞进固定大小虚拟线程池；每个任务保留自然阻塞栈。",
        signal: "THREAD PER TASK",
      },
      {
        label: "争取资源",
        actor: "virtual thread",
        action: "permits.acquire()",
        before: "资源容量=20",
        after: "20 active / 980 waiting",
        detail: "等待许可不会伪装成执行器排队，容量语义直接对应下游。",
        signal: "BULKHEAD",
      },
      {
        label: "进入调用",
        actor: "20 winners",
        action: "call.call()",
        before: "持有许可",
        after: "阻塞 I/O",
        detail: "支持的阻塞操作可卸载 carrier，使少量平台线程继续承载其他虚拟线程。",
        signal: "UNMOUNT",
      },
      {
        label: "观察 pinning",
        actor: "JVM / JFR",
        action: "carrier unavailable",
        before: "在特定临界区内阻塞",
        after: "虚拟线程固定 carrier",
        detail: "触发条件随 JDK 演进；用目标版本事件和实际栈诊断，不机械替换所有锁。",
        signal: "PINNING RISK",
      },
      {
        label: "释放资源",
        actor: "finally",
        action: "active-- / release",
        before: "调用成功或失败",
        after: "下一个等待任务进入",
        detail: "许可在所有出口归还，最大真实资源并发始终不超过 20。",
        signal: "CAPACITY HANDOFF",
      },
      {
        label: "收集整组",
        actor: "parent",
        action: "invokeAll(timeout) / get",
        before: "部分任务未完成",
        after: "success/failure/cancelled",
        detail: "整组共享时间边界，父任务负责取消未完成工作并关闭执行器。",
        signal: "OWNED LIFECYCLE",
      },
    ],
    zones: [
      {
        code: "VT",
        name: "virtual threads",
        kind: "轻量任务载体",
        owner: "每个 Callable",
        value: "0…请求任务数",
        mutation: "创建、阻塞、完成",
        rule: "通常每任务创建，不以池大小表达资源。",
      },
      {
        code: "CT",
        name: "carrier threads",
        kind: "平台执行载体",
        owner: "JVM scheduler",
        value: "约 CPU/调度所需数量",
        mutation: "挂载不同虚拟线程",
        rule: "pinning 时暂时无法承载其他虚拟线程。",
      },
      {
        code: "P",
        name: "resource permits",
        kind: "真实下游容量",
        owner: "Semaphore / connection pool",
        value: "0…20 active",
        mutation: "acquire / finally release",
        rule: "容量依据下游，不依据线程成本。",
      },
      {
        code: "TL",
        name: "ThreadLocal data",
        kind: "每虚拟线程状态",
        owner: "每个虚拟线程",
        value: "request context / cache",
        mutation: "set / remove",
        rule: "大对象乘以大量线程会放大内存。",
      },
    ],
    routes: [
      {
        data: "Callable",
        from: "父任务",
        via: "virtual-thread executor",
        to: "独立虚拟线程",
        guarantee: "直接阻塞式代码与独立栈",
      },
      {
        data: "资源许可",
        from: "Semaphore",
        via: "acquire",
        to: "最多 N 个虚拟线程",
        guarantee: "真实在途并发受限",
      },
      {
        data: "阻塞 continuation",
        from: "virtual thread",
        via: "JVM unmount/remount",
        to: "carrier",
        guarantee: "支持的阻塞点释放载体",
      },
      {
        data: "取消与异常",
        from: "子任务",
        via: "Future/structured scope",
        to: "父任务",
        guarantee: "生命周期由父级收集",
      },
    ],
    sourceKeys: ["13-virtual", "13-capacity", "13-exercise"],
    exercise: {
      title: "虚拟线程 + Semaphore 资源限流",
      summary:
        "每个调用使用独立虚拟线程，但外部资源并发由明确容量的 Semaphore 控制，并正确关闭执行器。",
      requirements: [
        "try-with-resources 管理虚拟线程执行器",
        "每个调用提交到独立虚拟线程",
        "成功 acquire 后在 finally release",
        "正确收集并传播失败，不泄漏执行器或许可",
      ],
      testCommand: "mvn -Dtest=VirtualResourceExerciseTest test",
      expected: "任务数可远大于资源容量，maxObserved 始终不超过 resourceCapacity。",
    },
    runClass: "com.caesaemc.juc.lesson13.Lesson13Application",
    interview: [
      {
        tag: "区别",
        question: "虚拟线程与平台线程有什么不同？",
        answer: "平台线程通常映射 OS 线程；虚拟线程由 JVM 调度，可在支持的阻塞点卸载 carrier，以低成本承载大量阻塞任务。",
      },
      {
        tag: "池化",
        question: "虚拟线程需要池吗？",
        answer: "通常每任务创建；资源容量用 Semaphore、连接池等单独表达，不用固定虚拟线程数量表达。",
      },
      {
        tag: "CPU",
        question: "虚拟线程适合 CPU 密集任务吗？",
        answer: "不会增加物理核心；CPU 并行度仍受核心数约束，ForkJoin 或固定平台池更便于控制。",
      },
      {
        tag: "pinning",
        question: "什么是 pinning？",
        answer: "虚拟线程阻塞时无法从 carrier 卸载；触发条件随 JDK 版本变化，应结合目标版本、JFR 与实际栈诊断。",
      },
      {
        tag: "结构化",
        question: "结构化并发解决什么？",
        answer: "让父任务拥有子任务生命周期，统一 join、失败、取消和截止时间，减少子任务泄漏并改善可观测性。",
      },
    ],
    finish:
      "能明确画出“任务数量 → 虚拟线程”和“真实资源 → Semaphore/连接池”两条互不混淆的容量线。",
  },
  {
    number: "14",
    stage: 4,
    title: "并发设计模式与可靠性",
    shortTitle: "模式是一组完整生命周期协议",
    english: "RELIABILITY PATTERNS",
    hook: "真正的 Bulkhead 不只是一个 Semaphore，而是容量、等待、失败、降级和指标。",
    lead:
      "从减少共享状态开始，把 Memoizer、DeadlineBudget 与 Bulkhead 组合成一个可说明正常、失败、超时、取消和关闭的设计。",
    outcome: "能提交一份包含所有权、容量、时间、失败、背压、指标与关闭的并发设计。",
    accent: "cyan",
    concepts: [
      {
        code: "O",
        title: "状态与所有权",
        subtitle: "reduce sharing first",
        body: "优先不可变值、线程封闭和消息传递；只有必须共享且维护多变量不变量时才引入显式锁。",
        boundary: "持锁调用未知 I/O 会把局部不变量放大成系统级阻塞风险。",
      },
      {
        code: "M",
        title: "Memoizer 单飞",
        subtitle: "cache Future, not only value",
        body: "缓存正在进行的 Future，让同 key 并发调用者共享加载；失败或取消后删除原 Future 允许重试。",
        boundary: "还需设计 TTL、最大容量、永久阻塞、退避与失效期间的单飞语义。",
      },
      {
        code: "D",
        title: "Deadline + Bulkhead",
        subtitle: "time and capacity",
        body: "入口记录绝对 deadline，每步取剩余预算与单步上限最小值；许可获取本身也计入预算。",
        boundary: "每层重置 timeout 会让总时长累加；资源容量不等于线程数量。",
      },
    ],
    flowTitle: "一个同 key 请求如何经过缓存、预算与隔离舱",
    flowLead:
      "相同请求先在 Memoizer 合流；真正需要加载的唯一任务，再使用共享 deadline 限时取得资源许可。",
    flow: [
      {
        label: "检查在途计算",
        actor: "Memoizer",
        action: "cache.get(key)",
        before: "key 不存在",
        after: "准备 FutureTask candidate",
        detail: "读取的是代表现在或未来结果的 Future，不只是已经完成的值。",
        signal: "LOOKUP",
      },
      {
        label: "赢得单飞",
        actor: "first caller",
        action: "putIfAbsent",
        before: "多个 candidate",
        after: "缓存一个 Future",
        detail: "只有返回 null 的调用者运行 candidate，其他调用者等待同一个 Future。",
        signal: "SINGLE FLIGHT",
      },
      {
        label: "计算剩余预算",
        actor: "DeadlineBudget",
        action: "cap(stepTimeout)",
        before: "overall deadline 固定",
        after: "remaining=min(step, overall)",
        detail: "System.nanoTime 用于经过时间，后续步骤不会重新获得完整预算。",
        signal: "TIME BUDGET",
      },
      {
        label: "进入隔离舱",
        actor: "Bulkhead",
        action: "tryAcquire(remaining)",
        before: "resource permits=N",
        after: "许可或 fallback",
        detail: "等待资源也消耗总预算，满载时快速降级而不是无限堆积。",
        signal: "ADMISSION",
      },
      {
        label: "加载与释放",
        actor: "loader",
        action: "call → finally release",
        before: "持有许可",
        after: "Future 完成 / 许可恢复",
        detail: "成功、失败和中断都汇合到 finally；结果唤醒所有同 key 等待者。",
        signal: "COMPLETE",
      },
      {
        label: "失败清除",
        actor: "Memoizer",
        action: "remove(key, future)",
        before: "Future 失败或取消",
        after: "下一次允许重试",
        detail: "条件 remove 只删除当前失败实例，避免误删已替换的新 Future。",
        signal: "RETRYABLE",
      },
    ],
    zones: [
      {
        code: "C",
        name: "cache<K, Future<V>>",
        kind: "并发共享单飞表",
        owner: "Memoizer",
        value: "key → in-flight/completed Future",
        mutation: "putIfAbsent / conditional remove",
        rule: "同 key 并发者共享同一计算。",
      },
      {
        code: "D",
        name: "deadlineNanos",
        kind: "不可变绝对时间",
        owner: "请求作用域",
        value: "入口 now + budget",
        mutation: "不变，只计算 remaining",
        rule: "所有步骤共享同一截止点。",
      },
      {
        code: "P",
        name: "bulkhead permits",
        kind: "下游资源容量",
        owner: "Semaphore",
        value: "0…capacity",
        mutation: "限时 acquire / finally release",
        rule: "中断与超时含义不能混淆。",
      },
      {
        code: "O",
        name: "Outcome",
        kind: "多结果协议",
        owner: "聚合器",
        value: "success/failure/timeout",
        mutation: "每个下游终态一次形成",
        rule: "核心与非核心策略由上层决定。",
      },
    ],
    routes: [
      {
        data: "相同 key 请求",
        from: "多个调用者",
        via: "putIfAbsent Future",
        to: "一个 loader",
        guarantee: "合并并发击穿",
      },
      {
        data: "时间预算",
        from: "入口 deadline",
        via: "remaining / cap",
        to: "每一步 timeout",
        guarantee: "总时长不按步骤累加",
      },
      {
        data: "资源许可",
        from: "Bulkhead",
        via: "限时 acquire",
        to: "loader",
        guarantee: "满载可降级",
      },
      {
        data: "失败 Future",
        from: "loader",
        via: "conditional remove",
        to: "下一次请求",
        guarantee: "暂时故障不会永久缓存",
      },
    ],
    sourceKeys: ["14-deadline", "14-memoizer", "14-exercise"],
    exercise: {
      title: "实现限时 Bulkhead",
      summary:
        "用公平 Semaphore 限制并发，限时获取失败时返回 fallback，成功获取后在所有路径释放。",
      requirements: [
        "校验 capacity 并创建公平 Semaphore",
        "使用 timeout 限时获取许可",
        "未获得许可返回 fallback",
        "获得许可后 finally release，中断继续向上传播",
      ],
      testCommand: "mvn -Dtest=BulkheadExerciseTest test",
      expected: "容量不被突破，满载按时降级，异常与中断不会造成许可泄漏。",
    },
    runClass: "com.caesaemc.juc.lesson14.Lesson14Application",
    interview: [
      {
        tag: "原则",
        question: "为什么优先不可变和线程封闭？",
        answer: "它们直接消除或减少共享可变状态，不依赖所有访问者都正确加锁，组合和维护成本最低。",
      },
      {
        tag: "Memoizer",
        question: "为什么缓存 Future 而不是最终值？",
        answer: "Future 同时代表进行中的计算和最终结果，并发调用者可共享同一次加载，避免缓存击穿。",
      },
      {
        tag: "失败",
        question: "失败结果应永久留在 Memoizer 吗？",
        answer: "通常不应。暂时故障会变成永久故障；应条件删除失败 Future，并结合退避、熔断避免重试风暴。",
      },
      {
        tag: "时间",
        question: "timeout 与 deadline 的区别？",
        answer: "timeout 是某一步最多等待多久；deadline 是整条链必须结束的绝对时刻，每步从剩余时间取预算。",
      },
      {
        tag: "容量",
        question: "Semaphore 与线程池限制的是同一件事吗？",
        answer: "不一定。线程池限制执行载体及排队；Semaphore 应表达具体稀缺资源，虚拟线程场景尤其要分开。",
      },
    ],
    finish:
      "能用“状态、所有权、容量、时间、失败、取消、背压、指标、关闭”九项清单评审一份并发设计。",
  },
  {
    number: "15",
    stage: 4,
    title: "并发测试、诊断与性能",
    shortTitle: "先构造证据，再给出根因",
    english: "TEST / DUMP / JFR / JMH",
    hook: "sleep 只能制造希望，Latch 才能制造时序。",
    lead:
      "用 ready/start 两道门闩稳定控制 actor，再把 JUnit、jcstress、JMH、负载测试、线程 dump 与 JFR 放进各自证据层。",
    outcome: "能完成“现象→证据→根因→修复→回归”的并发诊断闭环。",
    accent: "red",
    concepts: [
      {
        code: "T",
        title: "确定性时序",
        subtitle: "ready + start + deadline",
        body: "所有 actor 先进入 ready，再一次开放 start；准备和结果收集共用 deadline，失败时取消其余任务。",
        boundary: "sleep 不证明另一个线程到达某状态，也不建立业务所需 happens-before。",
      },
      {
        code: "4",
        title: "四种验证工具",
        subtitle: "JUnit / jcstress / JMH / load",
        body: "单元测试验证协议，jcstress 探索 JMM 结果，JMH 测量微观性能，负载测试观察系统容量与尾延迟。",
        boundary: "性能快不能证明线程安全，测试通过也不能替代规范推理。",
      },
      {
        code: "E",
        title: "证据链",
        subtitle: "dump + metrics + JFR",
        body: "线程状态与栈解释等待位置，指标解释规模和趋势，JFR 提供一段时间内的 CPU、park、monitor 与分配事件。",
        boundary: "一次 dump 是照片；吞吐和竞争问题通常需要多份样本与时间序列。",
      },
    ],
    flowTitle: "一次稳定并发测试如何运行",
    flowLead:
      "测试先确保 actor 全部就绪，再同时释放；任何准备、执行或收集阶段都不能超出同一个 deadline。",
    flow: [
      {
        label: "创建预算",
        actor: "test thread",
        action: "DeadlineBudget.after",
        before: "timeout 参数",
        after: "absolute deadline",
        detail: "整个测试只有一个时间边界，缺陷不会让构建永久挂起。",
        signal: "BOUNDED TEST",
      },
      {
        label: "提交 actors",
        actor: "executor",
        action: "submit wrappers",
        before: "N 个 Callable",
        after: "N 个 Future",
        detail: "每个包装先 ready.countDown，再等待同一个 start latch。",
        signal: "ARMED",
      },
      {
        label: "确认就绪",
        actor: "ready latch",
        action: "await(remaining)",
        before: "ready=N",
        after: "ready=0",
        detail: "这一步证明 actor 已经到起跑线，而不是依赖调度概率。",
        signal: "READY",
      },
      {
        label: "同时起跑",
        actor: "test thread",
        action: "start.countDown",
        before: "所有 actor WAITING",
        after: "竞争动作同时可运行",
        detail: "建立明确开始事件，构造目标交错或竞争窗口。",
        signal: "GO",
      },
      {
        label: "限时收集",
        actor: "Future list",
        action: "get(remaining)",
        before: "actors 执行",
        after: "结果列表或失败",
        detail: "每次 get 使用剩余预算；超时、异常或中断都取消其余 Future。",
        signal: "COLLECT",
      },
      {
        label: "形成诊断闭环",
        actor: "engineer",
        action: "dump + metric + JFR",
        before: "可复现现象",
        after: "根因与回归证据",
        detail: "修复后在同模型比较正确性、P99、队列、拒绝和资源使用。",
        signal: "PROOF",
      },
    ],
    zones: [
      {
        code: "R",
        name: "ready latch",
        kind: "准备阶段计数",
        owner: "test harness",
        value: "actorCount → 0",
        mutation: "每个 actor 到达时 countDown",
        rule: "证明所有 actor 已就绪。",
      },
      {
        code: "S",
        name: "start latch",
        kind: "一次性起跑门",
        owner: "test thread",
        value: "1 → 0",
        mutation: "测试线程一次释放",
        rule: "统一打开竞争窗口。",
      },
      {
        code: "Q",
        name: "backlog queue",
        kind: "故障实验积压",
        owner: "InstrumentedThreadPool",
        value: "0 → 80 queued",
        mutation: "worker 阻塞后持续 submit",
        rule: "结合 active、完成速率和等待时间解释。",
      },
      {
        code: "J",
        name: "JFR recording",
        kind: "时间序列事件",
        owner: "JVM",
        value: "CPU/park/monitor/allocation",
        mutation: "录制窗口持续追加",
        rule: "用事件与业务指标交叉验证。",
      },
    ],
    routes: [
      {
        data: "actor readiness",
        from: "每个测试线程",
        via: "ready.countDown",
        to: "test thread",
        guarantee: "开始前全部到位",
      },
      {
        data: "start signal",
        from: "test thread",
        via: "start latch",
        to: "所有 actors",
        guarantee: "一次性统一释放",
      },
      {
        data: "任务结果/异常",
        from: "actors",
        via: "Future + shared deadline",
        to: "assertions",
        guarantee: "有限时且传播失败",
      },
      {
        data: "运行证据",
        from: "JVM / pool / OS",
        via: "dump + metrics + JFR",
        to: "诊断报告",
        guarantee: "从现象追到可验证根因",
      },
    ],
    sourceKeys: ["15-harness", "15-diagnostic", "15-exercise"],
    exercise: {
      title: "稳定构造丢失更新并提交故障报告",
      summary:
        "不用 sleep，让两个 actor 都读取同一旧值后再写回；随后对 deadlock、spin、backlog、contention 建立证据链。",
      requirements: [
        "用两个阶段同步点控制读取与写回",
        "每次稳定得到实际值 1",
        "四类故障各记录 dump 关键栈与相关指标",
        "修复方案必须配套可重复回归验证",
      ],
      testCommand: "mvn -Dtest=DeterministicRaceExerciseTest,Lesson15Test test",
      expected: "竞态无需概率即可复现；故障报告包含现象、证据、根因、修复和回归。",
    },
    runClass: "com.caesaemc.juc.lesson15.Lesson15Application",
    interview: [
      {
        tag: "测试",
        question: "为什么并发测试不应依赖 sleep？",
        answer: "sleep 不证明另一个线程已到目标状态，也不建立业务同步边；机器负载变化会造成漏测或偶发失败。",
      },
      {
        tag: "工具",
        question: "JUnit 与 jcstress 的区别？",
        answer: "JUnit 验证业务协议与可构造不变量；jcstress 大量探索 JMM 下的结果集合并分类。",
      },
      {
        tag: "基准",
        question: "为什么不能直接 nanoTime 循环做微基准？",
        answer: "JIT 预热、死代码消除、常量折叠、GC、fork 隔离与测量开销都会扭曲结果。",
      },
      {
        tag: "队列",
        question: "线程池队列持续增长说明什么？",
        answer: "长期到达率高于完成率，或 worker 被慢/阻塞任务占用；要同时看 active、完成速率、等待和下游。",
      },
      {
        tag: "CPU",
        question: "如何诊断 CPU 空转？",
        answer: "定位高 CPU 系统线程并映射到 JVM 线程，多次抓栈；同一 RUNNABLE 栈持续出现后用 JFR/剖析器确认。",
      },
    ],
    finish:
      "能为一次并发事故写出：现象、最小复现、线程/指标/JFR 证据、根因、修复和同环境回归对比。",
  },
  {
    number: "16",
    stage: 4,
    title: "高并发多下游聚合服务",
    shortTitle: "把前 15 课组合成一个生产内核",
    english: "CAPSTONE AGGREGATION SERVICE",
    hook: "最后一课不再学孤立 API，而是让时间、容量、失败和生命周期在同一请求里闭环。",
    lead:
      "一次请求扇出多个下游，共享 overall deadline；平台池或虚拟线程承载任务，Semaphore 保护资源，五种终态稳定回流。",
    outcome: "能设计、运行、压测、诊断并答辩一套高并发聚合服务。",
    accent: "amber",
    concepts: [
      {
        code: "5",
        title: "五种稳定终态",
        subtitle: "success / failed / timed out / rejected / cancelled",
        body: "每个下游只进入一个终态，上层据此区分业务失败、时间不足、本地过载与上游放弃。",
        boundary: "把所有失败混成一个异常会误导重试、告警、降级和容量决策。",
      },
      {
        code: "2",
        title: "双层时间边界",
        subtitle: "overall + per call",
        body: "每个取消计时取单下游 timeout 与整体剩余预算的最小值；结果收集始终使用同一个 overall deadline。",
        boundary: "Future.cancel(true) 不保证远端停止，真实客户端取消必须单独验证。",
      },
      {
        code: "P/V",
        title: "两种执行模型",
        subtitle: "bounded platform / virtual per task",
        body: "平台版用固定 worker、有界队列和 Abort 背压；虚拟版每任务一线程，真实容量仍由 Semaphore 控制。",
        boundary: "比较两者时必须保持资源许可、负载、超时和机器环境相同。",
      },
    ],
    flowTitle: "一次聚合请求的完整数据流",
    flowLead:
      "从 DownstreamCall[] 输入开始，逐个建立任务与定时取消，穿过 worker、队列和资源许可，最后按输入顺序形成响应。",
    flow: [
      {
        label: "验证与预算",
        actor: "aggregate",
        action: "validate + DeadlineBudget.after",
        before: "DownstreamCall[] + overallTimeout",
        after: "唯一名称 + absolute deadline",
        detail: "入口先保证协议有效，并为整组调用只创建一个时间预算。",
        signal: "REQUEST SCOPE",
      },
      {
        label: "提交下游",
        actor: "workers",
        action: "submit(call)",
        before: "每个调用带 timeout/critical",
        after: "Future 或 REJECTED",
        detail: "平台队列饱和时立即记录 REJECTED；虚拟版为每个调用创建虚拟线程。",
        signal: "FAN OUT",
      },
      {
        label: "安排取消",
        actor: "timeout scheduler",
        action: "schedule(cancel)",
        before: "future 已提交",
        after: "min(perCall, remaining) timer",
        detail: "每个 Future 有独立定时器，但所有延迟都受同一个整体截止点约束。",
        signal: "TIME GUARD",
      },
      {
        label: "取得资源",
        actor: "worker task",
        action: "resourcePermits.acquire",
        before: "任务已开始",
        after: "进入下游或等待",
        detail: "执行载体与真实资源容量分离；许可在 finally 中归还。",
        signal: "BULKHEAD",
      },
      {
        label: "形成终态",
        actor: "CallOutcome",
        action: "success/fail/timeout/reject/cancel",
        before: "下游运行或被停止",
        after: "唯一稳定结果",
        detail: "terminalRecorded CAS 确保每个输入调用只记录一次终态指标。",
        signal: "TERMINAL",
      },
      {
        label: "有序聚合",
        actor: "AggregationResponse",
        action: "collect by original index",
        before: "outcomes[] 部分填充",
        after: "完整响应 + degraded/critical failure",
        detail: "输出顺序与输入一致，上层用 critical 标记做 OK/PARTIAL/FAILED 决策。",
        signal: "FAN IN",
      },
    ],
    zones: [
      {
        code: "IN",
        name: "DownstreamCall[]",
        kind: "不可变请求计划",
        owner: "一次 aggregate 调用",
        value: "name/action/timeout/critical",
        mutation: "不修改",
        rule: "名称唯一，输入顺序稳定。",
      },
      {
        code: "Q",
        name: "platform queue",
        kind: "有界排队容量",
        owner: "PlatformAggregationService",
        value: "0…queueCapacity",
        mutation: "submit / Worker take",
        rule: "满载转为 REJECTED，不静默丢弃。",
      },
      {
        code: "P",
        name: "resource permits",
        kind: "真实下游容量",
        owner: "AbstractAggregationService",
        value: "0…resourceCapacity active",
        mutation: "acquire / finally release",
        rule: "平台与虚拟版本共享同一容量事实。",
      },
      {
        code: "OUT",
        name: "CallOutcome[]",
        kind: "按输入索引的终态数组",
        owner: "聚合请求",
        value: "5 种互斥状态",
        mutation: "每个 index 一次完成",
        rule: "结果与指标每个调用只记一次。",
      },
    ],
    routes: [
      {
        data: "DownstreamCall",
        from: "请求计划",
        via: "worker submit",
        to: "平台/虚拟任务",
        guarantee: "提交失败显式 REJECTED",
      },
      {
        data: "时间预算",
        from: "overall deadline",
        via: "min(per-call, remaining)",
        to: "timer + result await",
        guarantee: "总等待不按下游数累加",
      },
      {
        data: "资源许可",
        from: "Semaphore",
        via: "acquire / finally",
        to: "实际下游调用",
        guarantee: "真实并发不超过容量",
      },
      {
        data: "CallOutcome",
        from: "每个下游",
        via: "original index",
        to: "AggregationResponse",
        guarantee: "顺序稳定、部分结果保留",
      },
    ],
    sourceKeys: ["16-engine", "16-platform", "16-virtual", "16-exercise"],
    exercise: {
      title: "完成降级决策与容量设计",
      summary:
        "把底层五种终态映射成 OK/PARTIAL/FAILED，并为 1,000 RPS、四下游和 200ms 总预算设计容量。",
      requirements: [
        "全部成功为 OK，仅非关键失败为 PARTIAL",
        "任一关键调用非成功为 FAILED",
        "为每个下游独立说明 Bulkhead 与依据",
        "对平台/虚拟版本执行相同负载、JFR 与故障注入",
      ],
      testCommand: "mvn -Dtest=DegradationPolicyExerciseTest,Lesson16Test test",
      expected: "降级协议准确，资源并发受限，超时/拒绝/取消指标与输入调用数一致。",
    },
    runClass: "com.caesaemc.juc.lesson16.CapstoneApplication",
    interview: [
      {
        tag: "时间",
        question: "为什么同时需要 overall deadline 与 per-call timeout？",
        answer: "单下游上限防止一个依赖占满预算；overall deadline 保证整条请求不会因顺序等待累加。",
      },
      {
        tag: "背压",
        question: "有界队列为什么比无界队列安全？",
        answer: "无界队列把过载变成内存与尾延迟增长；有限队列给出明确饱和信号，允许快速拒绝或降级。",
      },
      {
        tag: "虚拟线程",
        question: "虚拟线程版的背压在哪里？",
        answer: "真实资源由 Semaphore/连接池限并发，等待受 deadline 限制；入口还应限制最大在途请求。",
      },
      {
        tag: "取消",
        question: "Future.cancel(true) 是否保证远端停止？",
        answer: "不保证。任务、驱动和协议必须合作，需要针对实际 HTTP/数据库客户端验证取消与连接释放。",
      },
      {
        tag: "模型",
        question: "如何选择平台线程池或虚拟线程？",
        answer: "看阻塞比例、目标 JDK、依赖取消能力、ThreadLocal、pinning、监控和容量模型，并在相同资源限制下实测。",
      },
    ],
    finish:
      "能在白板上完整讲清提交、排队、许可、执行、定时取消、五种终态、有序收集、降级和优雅关闭。",
  },
];

export function getLessonDetail(number: string) {
  return lessonDetails.find((lesson) => lesson.number === number);
}

export function getLessonSources(lesson: LessonDetail): SourceSnippet[] {
  return lesson.sourceKeys.map((key) => {
    const source = sourceSnippetByKey[key];
    if (!source) {
      throw new Error(`课程 ${lesson.number} 缺少源码片段：${key}`);
    }
    return source;
  });
}

export function lessonGithubUrl(number: string, file = "README.md") {
  return `https://github.com/caesaemc/JucCoreImp/blob/main/docs/lesson-${number}/${file}`;
}
